#!/usr/bin/env python3
"""Gate: verify that declared SHA256 manifests match on-disk files.

This gate strengthens reproducibility by checking *hash integrity* (not just file
presence). It validates:
  - 00_metadata/MANIFEST.sha256  (root bundle manifest)
  - 01_quantum_annihilation/quantum_annihilation_DOI_vNext/MANIFEST.sha256
  - 02_lattice_percolation_soc/lattice_percolation_soc_bundle/manifest_sha256.txt
  - 03_qm_proton_whitepaper/MANIFEST.sha256

Design note about determinism
-----------------------------
The bundle contains generated snapshot artifacts under snapshot/. Those can be
regenerated by scripts/seal_snapshot.py. To avoid a self-referential "fixed
point" problem (a gate report is itself a file that would then alter snapshot
hashes), this gate *skips* snapshot/ entries when checking the root manifest.

It also skips its own gate report file(s).

Output:
  gate/reports/gate_report_MANIFEST_HASH.json

No third-party dependencies.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def protocol_created(root: Path) -> str:
    p = root / "registry" / "protocol_lock.json"
    if p.exists():
        try:
            v = read_json(p).get("created")
            if v:
                return str(v)
        except Exception:
            pass
    return str(date.today())


@dataclass(frozen=True)
class ManifestSpec:
    name: str
    path: Path
    base_dir: Path
    # relative paths (after stripping leading "./") that start with any of these
    # prefixes will be skipped.
    skip_prefixes: Tuple[str, ...] = ()
    # relative paths that exactly match these will be skipped.
    skip_exact: Tuple[str, ...] = ()


def parse_manifest_lines(text: str) -> List[Tuple[str, str]]:
    """Return list[(expected_hash, rel_path_str)] from a sha256sum-style manifest."""
    out: List[Tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # sha256sum format: "<hash><two spaces><path>"; paths may contain spaces.
        try:
            expected, rel_raw = line.split(maxsplit=1)
        except ValueError:
            continue
        expected = expected.strip()
        rel_raw = rel_raw.strip()

        # Normalize a leading "./" (but do NOT strip a leading dot in filenames
        # like ".zenodo.json").
        if rel_raw.startswith("./") or rel_raw.startswith(".\\"):
            rel = rel_raw[2:]
        else:
            rel = rel_raw
        out.append((expected, rel))
    return out


def should_skip(rel: str, spec: ManifestSpec) -> bool:
    if rel in spec.skip_exact:
        return True
    for pref in spec.skip_prefixes:
        if rel.startswith(pref):
            return True
    return False


def check_manifest(spec: ManifestSpec) -> Dict[str, object]:
    lines = parse_manifest_lines(spec.path.read_text(encoding="utf-8"))

    missing: List[str] = []
    mismatches: List[Dict[str, str]] = []

    checked = 0
    skipped = 0

    for expected, rel in lines:
        if should_skip(rel, spec):
            skipped += 1
            continue
        target = spec.base_dir / rel
        if not target.exists():
            missing.append(rel)
            continue
        got = sha256_file(target)
        checked += 1
        if got != expected:
            mismatches.append({"path": rel, "expected": expected, "got": got})

    return {
        "manifest": str(spec.path.relative_to(spec.base_dir.parent if spec.base_dir != spec.base_dir.parent else spec.base_dir)),
        "name": spec.name,
        "entries_total": len(lines),
        "entries_checked": checked,
        "entries_skipped": skipped,
        "missing_count": len(missing),
        "mismatch_count": len(mismatches),
        "missing": missing,
        "mismatches": mismatches,
    }


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    created = protocol_created(root)

    # Root manifest: skip snapshot/ to avoid a self-referential fixed point.
    # Also skip this gate's own report outputs.
    root_spec = ManifestSpec(
        name="root",
        path=root / "00_metadata" / "MANIFEST.sha256",
        base_dir=root,
        skip_prefixes=(
            "snapshot/",
            "exp10/snapshot/",
        ),
        skip_exact=(
            "gate/reports/gate_report_MANIFEST_HASH.json",
            "gate/reports/gate_report_MANIFEST_HASH.tex",
        ),
    )

    specs = [
        root_spec,
        ManifestSpec(
            name="quantum_annihilation",
            path=root / "01_quantum_annihilation" / "quantum_annihilation_DOI_vNext" / "MANIFEST.sha256",
            base_dir=root / "01_quantum_annihilation" / "quantum_annihilation_DOI_vNext",
        ),
        ManifestSpec(
            name="lattice_percolation_soc",
            path=root / "02_lattice_percolation_soc" / "lattice_percolation_soc_bundle" / "manifest_sha256.txt",
            base_dir=root / "02_lattice_percolation_soc" / "lattice_percolation_soc_bundle",
        ),
        ManifestSpec(
            name="qm_proton_whitepaper",
            path=root / "03_qm_proton_whitepaper" / "MANIFEST.sha256",
            base_dir=root / "03_qm_proton_whitepaper",
        ),
    ]

    results = [check_manifest(s) for s in specs]

    any_fail = any((r["missing_count"] or r["mismatch_count"]) for r in results)
    status = "PASS" if not any_fail else "FAIL"

    # Keep details compact: list all missing/mismatches for small bundles, but
    # cap to avoid huge reports.
    def cap_list(xs: List, n: int = 50):
        return xs[:n] + ([{"_truncated": f"... {len(xs) - n} more"}] if len(xs) > n else [])

    details = {
        "status": status,
        "manifests_checked": [
            {
                "name": r["name"],
                "path": str(specs[i].path.relative_to(root)),
                "entries_total": r["entries_total"],
                "entries_checked": r["entries_checked"],
                "entries_skipped": r["entries_skipped"],
                "missing_count": r["missing_count"],
                "mismatch_count": r["mismatch_count"],
                "missing": cap_list(r["missing"], 50),
                "mismatches": cap_list(r["mismatches"], 50),
            }
            for i, r in enumerate(results)
        ],
        "skip_policy": {
            "root_manifest": {
                "skip_prefixes": list(root_spec.skip_prefixes),
                "skip_exact": list(root_spec.skip_exact),
                "note": "snapshot/ entries are skipped to avoid a self-referential fixed point (snapshot is regenerable).",
            }
        },
    }

    # IMPORTANT: Do **not** embed the root MANIFEST.sha256 hash here.
    # The root manifest includes a hash entry for this gate report, so including
    # the root manifest hash inside the report would create a self-referential
    # cycle (report -> manifest -> report). We avoid that by only recording
    # hashes for the *submodule* manifests.
    manifest_sha = {}
    for s in specs:
        rel = str(s.path.relative_to(root))
        if rel == "00_metadata/MANIFEST.sha256":
            continue
        manifest_sha[rel] = sha256_file(s.path)

    evidence = {
        "manifest_sha256": manifest_sha,
        "root_manifest_note": "root MANIFEST.sha256 hash intentionally omitted to avoid a self-referential hash cycle",
        "generated_by": str(Path(__file__).relative_to(root)),
    }

    report = {
        "gate_id": "G-MANIFEST-HASH",
        "status": status,
        "created": created,
        "details": details,
        "evidence": evidence,
    }

    out = root / "gate" / "reports" / "gate_report_MANIFEST_HASH.json"
    write_json(out, report)

    print(f"[OK] wrote {out.relative_to(root)} (status={status})")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
