#!/usr/bin/env python3
"""Definitive V3 chemistry logic check (Sec.18.2): K-constant meaning + CH4 Rule-B.

This script strengthens the DOI's defense against 'black-box' criticism by adding
small, deterministic, machine-checkable derivations on top of the Step7
external-inspection dataset.

Checks performed
----------------
A) Constant K definition (non-arbitrary):
   K_coupling = 1000 * alpha_em.
   With r_cov(H)=31 pm and Beta_vac=1.088, the implied vacuum amplitude is:
     r_vac_pred = r_cov(H) * K_coupling * Beta_vac
   which is compared against the Step7 lock value r_vac_lock.

B) CH4 Rule B (leading-order form used in the V3 spec):
     P_idx(CH4) = PHI_GEO * (1 - DELTA_OV_sp3)
   where:
     PHI_GEO = pi/(3*sqrt(2))
     DELTA_OV_sp3 = 0.0132
   This is compared against the Step7 dataset row for CH4.

Outputs
-------
- 04_vp_whitepaper/outputs/chem/definitive_v3_check.json
- 04_vp_whitepaper/outputs/chem/table_definitive_v3_check.tex
- gate/reports/gate_report_CHEM_DEFINITIVE_V3.json

No third-party dependencies.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional


# ----------------------------
# Utilities
# ----------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding='utf-8')


def protocol_created(bundle_root: Path) -> str:
    """Deterministic date for reproducibility."""
    p = bundle_root / "registry" / "protocol_lock.json"
    if p.exists():
        try:
            v = load_json(p).get("created")
            if v:
                return str(v)
        except Exception:
            pass
    return str(date.today())


def read_csv_dicts(path: Path) -> List[dict]:
    rows: List[dict] = []
    with path.open('r', encoding='utf-8', newline='') as f:
        # Skip comment header lines starting with '#'
        # until we reach the real CSV header.
        pos = f.tell()
        first = f.readline()
        while first.startswith('#'):
            pos = f.tell()
            first = f.readline()
        f.seek(pos)

        reader = csv.DictReader(f)
        for row in reader:
            cleaned = {k.strip(): (v.strip() if isinstance(v, str) else v) for k, v in row.items()}
            # The external-inspection CSV includes section separators as comment rows
            # (e.g., ID begins with '#'). Treat them as non-data.
            if str(cleaned.get("ID", "")).startswith("#"):
                continue
            if not str(cleaned.get("ID", "")).strip():
                continue
            rows.append(cleaned)
    return rows


@dataclass
class CheckResult:
    name: str
    status: str
    details: Dict[str, object]


# ----------------------------
# LaTeX output
# ----------------------------

def latex_table(checks: List[CheckResult]) -> str:
    lines: List[str] = []
    lines.append(r"% Auto-generated by 04_vp_whitepaper/scripts/run_chem_definitive_v3.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\begin{tabular}{|l|c|l|}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Check} & \textbf{Status} & \textbf{Key numbers}\\ \hline")

    for c in checks:
        if c.name == "K_to_r_vac":
            key = (
                rf"$r_{{vac}}^{{pred}}={c.details['r_vac_pred_fm']:.3f}\,fm$, "
                rf"$r_{{vac}}^{{lock}}={c.details['r_vac_lock_fm']:.3f}\,fm$, "
                rf"$\Delta={c.details['diff_fm']:.3f}\,fm$"
            )
        elif c.name == "CH4_ruleB_leading":
            key = (
                rf"$P_{{idx}}^{{pred}}={c.details['P_idx_pred']:.6f}$, "
                rf"$P_{{idx}}^{{data}}={c.details['P_idx_data']:.4f}$, "
                rf"$\Delta={c.details['diff_abs']:.6f}$"
            )
        else:
            key = "-"

        lines.append(f"{c.name} & {c.status} & {key}\\ \\hline")

    lines.append(r"\end{tabular}")
    lines.append(r"\caption{Definitive V3 checks: constant $K$ meaning and CH$_4$ Rule-B reproduction}")
    lines.append(r"\label{tab:chem_definitive_v3}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


# ----------------------------
# Main
# ----------------------------

def main() -> int:
    # scripts/ is under 04_vp_whitepaper/; bundle_root is two levels up.
    bundle_root = Path(__file__).resolve().parents[2]
    created = protocol_created(bundle_root)

    lock_path = bundle_root / "04_vp_whitepaper" / "LOCK" / "chem_definitive_v3_lock.json"
    lock = load_json(lock_path)

    C = lock["constants"]
    tol = C.get("tolerances", {})
    tol_r_vac = float(tol.get("r_vac_abs_fm", 1.0))
    tol_pidx = float(tol.get("P_idx_abs", 0.01))

    # --- Check A: K -> r_vac
    r_cov_H_pm = float(C["r_cov_H_pm"])
    alpha_em = float(C["alpha_em"])
    Beta_vac = float(C["Beta_vac"])
    K = float(C["K_coupling"])
    r_vac_lock = float(C["r_vac_lock_fm"])

    r_vac_pred = r_cov_H_pm * K * Beta_vac
    diff_r = r_vac_pred - r_vac_lock

    status_A = "PASS" if abs(diff_r) <= tol_r_vac else "FAIL"

    check_A = CheckResult(
        name="K_to_r_vac",
        status=status_A,
        details={
            "alpha_em": alpha_em,
            "K_coupling": K,
            "r_cov_H_pm": r_cov_H_pm,
            "Beta_vac": Beta_vac,
            "r_vac_pred_fm": r_vac_pred,
            "r_vac_lock_fm": r_vac_lock,
            "diff_fm": diff_r,
            "tolerance_abs_fm": tol_r_vac,
        },
    )

    # --- Check B: CH4 Rule B (leading)
    dataset_path = bundle_root / lock["inputs"]["external_inspection_csv"]
    rows = read_csv_dicts(dataset_path)

    ch4_row: Optional[dict] = None
    for r in rows:
        # The external-inspection CSV uses FORMULA (older scripts sometimes use SPECIES).
        formula = r.get("SPECIES") or r.get("FORMULA") or ""
        if str(formula).strip() == "CH4":
            ch4_row = r
            break
    if ch4_row is None:
        raise RuntimeError("CH4 row not found in external inspection CSV")

    P_idx_data = float(ch4_row["P_IDX"])

    PHI_GEO = float(C["PHI_GEO"])
    DELTA_OV = float(C["DELTA_OV_sp3"])

    P_idx_pred = PHI_GEO * (1.0 - DELTA_OV)
    diff_p = P_idx_pred - P_idx_data

    status_B = "PASS" if abs(diff_p) <= tol_pidx else "FAIL"

    # Optional: compute P_avg for CH4 from Z/r^2 average (as described in V3 spec)
    r_cov_C_pm = float(C["r_cov_C_pm"])
    P_raw_H = 1.0 / (r_cov_H_pm ** 2)
    P_raw_C = 6.0 / (r_cov_C_pm ** 2)
    P_avg = (P_raw_C + 4.0 * P_raw_H) / 5.0
    P_avg_idx = P_avg / P_raw_H
    P_idx_full = P_avg_idx * PHI_GEO * (1.0 - DELTA_OV)

    check_B = CheckResult(
        name="CH4_ruleB_leading",
        status=status_B,
        details={
            "row_id": ch4_row.get("ID"),
            "P_idx_pred": P_idx_pred,
            "P_idx_data": P_idx_data,
            "diff_abs": diff_p,
            "tolerance_abs": tol_pidx,
            "PHI_GEO": PHI_GEO,
            "DELTA_OV": DELTA_OV,
            "P_avg_idx_CH4": P_avg_idx,
            "P_idx_full_with_P_avg": P_idx_full,
        },
    )

    checks = [check_A, check_B]
    overall = "PASS" if all(c.status == "PASS" for c in checks) else "FAIL"

    # --- Write outputs
    out_json = bundle_root / "04_vp_whitepaper" / "outputs" / "chem" / "definitive_v3_check.json"
    out_tex = bundle_root / "04_vp_whitepaper" / "outputs" / "chem" / "table_definitive_v3_check.tex"

    payload = {
        "DATA_SPEC_ID": "VP_STEP7_LOGIC_DEFINITIVE_V3",
        "created": created,
        "status": overall,
        "inputs": {
            "lock": str(lock_path.relative_to(bundle_root)),
            "dataset": str(dataset_path.relative_to(bundle_root)),
        },
        "checks": [
            {
                "name": c.name,
                "status": c.status,
                "details": c.details,
            }
            for c in checks
        ],
    }

    write_json(out_json, payload)
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(latex_table(checks), encoding='utf-8')

    # --- Gate report
    report = {
        "gate_id": "G-CHEM-DEFINITIVE-V3",
        "status": overall,
        "created": created,
        "details": {
            "checks": [
                {
                    "name": c.name,
                    "status": c.status,
                    "details": c.details,
                }
                for c in checks
            ]
        },
        "evidence": {
            "lock_sha256": sha256_file(lock_path),
            "dataset_sha256": sha256_file(dataset_path),
            "output_json_sha256": sha256_file(out_json),
            "generated_by": str(Path(__file__).relative_to(bundle_root)),
        },
    }

    out_report = bundle_root / "gate" / "reports" / "gate_report_CHEM_DEFINITIVE_V3.json"
    write_json(out_report, report)

    print(f"[OK] wrote {out_json.relative_to(bundle_root)}")
    print(f"[OK] wrote {out_tex.relative_to(bundle_root)}")
    print(f"[OK] wrote {out_report.relative_to(bundle_root)} (status={overall})")

    return 0 if overall == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
