#!/usr/bin/env python3
"""Rigidity theory v2.1: reproducible N_eff computation from modulus ratios.

This is a minimal, deterministic companion to Appendix H (Geometric Rigidity).

Inputs (locked):
- 04_vp_whitepaper/LOCK/rigidity_theory_v2_1_lock.json
- 04_vp_whitepaper/data/rigidity/rigidity_case_studies_v1.csv

Outputs:
- 04_vp_whitepaper/outputs/rigidity/rigidity_case_studies.json
- 04_vp_whitepaper/outputs/rigidity/table_rigidity_case_studies.tex
- gate/reports/gate_report_RIGIDITY_V2_1.json

Gate policy:
- Gates only internal mathematical consistency of the mapping
    ratio -> N_eff
  under the locked kappa, using a small set of expected rows.
- It does NOT claim experimental universality of the model.

No third-party dependencies.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import math
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding='utf-8')


def protocol_created(bundle_root: Path) -> str:
    """Deterministic date for reproducibility (preferred over wall-clock time)."""
    p = bundle_root / "registry" / "protocol_lock.json"
    if p.exists():
        try:
            v = load_json(p).get("created")
            if v:
                return str(v)
        except Exception:
            pass
    return str(date.today())


def read_csv_allow_comments(path: Path) -> List[dict]:
    lines: List[str] = []
    for ln in path.read_text(encoding='utf-8').splitlines():
        s = ln.strip()
        if not s:
            continue
        if s.startswith('#'):
            continue
        # allow a dataset header row like "DATASET_ID,..." as a comment-like metadata line
        if s.upper().startswith('DATASET_ID'):
            continue
        lines.append(ln)
    if not lines:
        return []
    reader = csv.DictReader(io.StringIO("\n".join(lines)))
    out: List[dict] = []
    for r in reader:
        out.append({k.strip(): (v.strip() if isinstance(v, str) else v) for k, v in r.items()})
    return out


def to_bool(s: str) -> bool:
    return str(s).strip().upper() in {"TRUE", "T", "1", "YES", "Y"}


def compute_N_eff(ratio: float, kappa: float) -> float:
    if ratio <= 0:
        raise ValueError("ratio must be positive")
    return 4.0 - 1.0 / (1.0 + (1.0 / kappa) * math.log(ratio))


def latex_table(rows: List[dict], kappa: float) -> str:
    lines: List[str] = []
    lines.append(r"% Auto-generated by 04_vp_whitepaper/scripts/run_rigidity_theory_v2_1.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\begin{tabular}{|l|l|r|r|l|}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Material} & \textbf{Transition} & \textbf{Ratio} & \textbf{$N_{eff}$} & \textbf{Note}\\ \hline")

    def fmt(x: Optional[float]) -> str:
        if x is None:
            return "N/A"
        return f"{x:.3f}"

    for r in rows:
        ratio = float(r["ratio_Ks_over_Kl"])
        neff = r.get("N_eff")
        note = r.get("notes", "")
        # Keep table compact
        if len(note) > 32:
            note = note[:29] + "..."
        lines.append(
            f"{r['material']} & {r['transition']} & {ratio:.2f} & {fmt(neff)} & {note}\\ \\hline"
        )

    lines.append(r"\end{tabular}")
    lines.append(rf"\caption{{Geometric Rigidity case studies (locked; $\kappa={kappa:g}$). $N_{{eff}}$ computed from ratio via $N_{{eff}} = 4 - 1/(1 + (1/\kappa)\ln(ratio))$.}}")
    lines.append(r"\label{tab:rigidity_case_studies}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main() -> int:
    bundle_root = Path(__file__).resolve().parents[2]
    created = protocol_created(bundle_root)
    lock_path = bundle_root / "04_vp_whitepaper" / "LOCK" / "rigidity_theory_v2_1_lock.json"
    lock = load_json(lock_path)

    kappa = float(lock["constants"]["kappa"])
    tol = float(lock["constants"]["tolerances"]["N_eff_abs"])

    csv_path = bundle_root / lock["inputs"]["case_studies_csv"]
    rows = read_csv_allow_comments(csv_path)
    if not rows:
        raise SystemExit(f"No rows in {csv_path}")

    out_rows: List[dict] = []
    for r in rows:
        material = r.get("material", "")
        ratio = float(r["ratio_Ks_over_Kl"])
        apply = to_bool(r.get("apply_model", "FALSE"))
        neff: Optional[float] = None
        if apply:
            neff = compute_N_eff(ratio, kappa)
        out_rows.append({
            "material": material,
            "transition": r.get("transition", ""),
            "ratio_Ks_over_Kl": ratio,
            "apply_model": apply,
            "N_eff": neff,
            "notes": r.get("notes", ""),
            "source_ref": r.get("source_ref", ""),
        })

    # Expected checks
    expected = lock["constants"].get("expected", {})
    checks: List[dict] = []
    ok = True

    # Build index for quick lookup
    idx = {r["material"]: r for r in out_rows}
    for mat, exp in expected.items():
        if mat not in idx:
            ok = False
            checks.append({
                "name": f"expected_row_present_{mat}",
                "pass": False,
                "got": None,
                "expected": "row present",
            })
            continue
        got_ratio = idx[mat]["ratio_Ks_over_Kl"]
        got_neff = idx[mat]["N_eff"]
        exp_ratio = float(exp["ratio"])
        exp_neff = float(exp["N_eff"])
        ratio_ok = abs(got_ratio - exp_ratio) < 1e-12
        neff_ok = (got_neff is not None) and (abs(got_neff - exp_neff) <= tol)
        ok = ok and ratio_ok and neff_ok
        checks.append({
            "name": f"expected_{mat}",
            "pass": bool(ratio_ok and neff_ok),
            "got": {"ratio": got_ratio, "N_eff": got_neff},
            "expected": {"ratio": exp_ratio, "N_eff": exp_neff},
            "tolerance_N_eff_abs": tol,
        })

    # Sanity: any apply_model rows must yield 3 < N_eff < 4
    for r in out_rows:
        if not r["apply_model"]:
            continue
        neff = r["N_eff"]
        sane = (neff is not None) and (3.0 < neff < 4.0)
        ok = ok and sane
        checks.append({
            "name": f"sanity_range_{r['material']}",
            "pass": bool(sane),
            "got": neff,
            "expected": "3 < N_eff < 4",
        })

    status = "PASS" if ok else "FAIL"

    # Outputs
    out_json = bundle_root / "04_vp_whitepaper" / "outputs" / "rigidity" / "rigidity_case_studies.json"
    out_tex = bundle_root / "04_vp_whitepaper" / "outputs" / "rigidity" / "table_rigidity_case_studies.tex"

    write_json(out_json, {
        "DATA_SPEC_ID": "VP_RIGIDITY_CASE_STUDIES_V1",
        "created": created,
        "kappa": kappa,
        "status": status,
        "inputs": {
            "lock": str(lock_path.relative_to(bundle_root)),
            "csv": str(csv_path.relative_to(bundle_root)),
        },
        "rows": out_rows,
        "checks": checks,
    })

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(latex_table(out_rows, kappa), encoding='utf-8')

    # Gate report
    gate_report = {
        "gate_id": "G-RIGIDITY-V2-1",
        "status": status,
        "created": created,
        "checks": checks,
        "evidence": {
            "lock_sha256": sha256_file(lock_path),
            "csv_sha256": sha256_file(csv_path),
            "output_json_sha256": sha256_file(out_json),
            "generated_by": str(Path(__file__).relative_to(bundle_root)),
        },
    }

    gate_path = bundle_root / "gate" / "reports" / "gate_report_RIGIDITY_V2_1.json"
    write_json(gate_path, gate_report)

    print(f"[OK] wrote {out_json.relative_to(bundle_root)}")
    print(f"[OK] wrote {out_tex.relative_to(bundle_root)}")
    print(f"[OK] wrote {gate_path.relative_to(bundle_root)} (status={status})")

    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
