#!/usr/bin/env python3
"""Bulk literature inspection validator for VP chemistry (Sec.18).

This script consumes a DOI-embedded CSV dataset containing (P_IDX, OBS_REF_AMP)
for a broad set of species and produces deterministic summary outputs.

Inputs (locked):
- 04_vp_whitepaper/LOCK/chem_external_inspection_lock.json
- 04_vp_whitepaper/data/chem/external_inspection/VP_STEP7_EXT_INSPECTION_FULL_V1.csv

Outputs:
- 04_vp_whitepaper/outputs/chem/external_inspection_rows.json
- 04_vp_whitepaper/outputs/chem/external_inspection_summary.json
- 04_vp_whitepaper/outputs/chem/table_external_inspection_summary.tex
- gate/reports/gate_report_chem_external_inspection.json

The gate is an **integrity** gate:
- it checks that the dataset is internally consistent with its declared rule
  (CALC_AMP, ERROR(%), STATUS vs tolerance)
- it does NOT require all rows to PASS as chemistry (the dataset intentionally
  contains explicit failures/boundary cases).

No non-std dependencies.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import math
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, List, Tuple


# ----------------------------
# Utilities
# ----------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding='utf-8')


def protocol_created(bundle_root: Path) -> str:
    """Deterministic date for reproducibility (preferred over wall-clock time)."""
    p = bundle_root / "registry" / "protocol_lock.json"
    if p.exists():
        try:
            v = load_json(p).get("created")
            if v:
                return str(v)
        except Exception:
            pass
    return str(date.today())


def read_csv_allow_comments(path: Path) -> List[dict]:
    """Read CSV while skipping comment/blank lines.

    Lines starting with '#' are ignored.
    """
    buf_lines: List[str] = []
    for ln in path.read_text(encoding='utf-8').splitlines():
        s = ln.strip()
        if not s:
            continue
        if s.startswith('#'):
            continue
        buf_lines.append(ln)
    if not buf_lines:
        return []
    reader = csv.DictReader(io.StringIO("\n".join(buf_lines)))
    rows: List[dict] = []
    for row in reader:
        cleaned = {k.strip(): (v.strip() if isinstance(v, str) else v) for k, v in row.items()}
        rows.append(cleaned)
    return rows


def pct(x: float) -> float:
    return 100.0 * x


@dataclass
class RowCheck:
    id: str
    ok: bool
    label: str
    got: float
    expected: float
    tol: float


# ----------------------------
# LaTeX generator
# ----------------------------

def latex_table_summary(summary: dict) -> str:
    rows = summary["group_stats"]

    lines: List[str] = []
    lines.append(r"% Auto-generated by 04_vp_whitepaper/scripts/run_chem_external_inspection.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\begin{tabular}{|l|r|r|r|r|}")
    lines.append(r"\hline")
    lines.append(r"\textbf{그룹} & \textbf{N} & \textbf{PASS} & \textbf{FAIL} & \textbf{통과율}\\ \hline")

    def fmt_rate(p: float) -> str:
        return f"{p:.1f}\\%"

    # Total first
    total = summary["total"]
    lines.append(
        f"Total & {total['n']} & {total['pass']} & {total['fail']} & {fmt_rate(total['pass_rate_pct'])}\\\\ \hline"
    )

    # Then each group (stable order)
    for g in sorted(rows.keys()):
        gs = rows[g]
        lines.append(
            f"{g} & {gs['n']} & {gs['pass']} & {gs['fail']} & {fmt_rate(gs['pass_rate_pct'])}\\\\ \hline"
        )

    lines.append(r"\end{tabular}")
    tol = summary.get("gate_tolerance_pct", 5.0)
    lines.append(rf"\caption{{문헌 기반 진폭 점검 데이터셋 요약 (허용오차 $\pm{tol:.1f}\%$)}}")
    lines.append(r"\label{tab:chem_external_inspection_summary}")
    lines.append(r"\end{table}")

    # Failure reason mini-table (optional)
    fr = summary.get("failure_reasons", {})
    if fr:
        lines.append("")
        lines.append(r"% Failure reason counts")
        lines.append(r"\begin{table}[h]")
        lines.append(r"\centering")
        lines.append(r"\begin{tabular}{|l|r|}")
        lines.append(r"\hline")
        lines.append(r"\textbf{FAIL 라벨} & \textbf{건수}\\ \hline")
        for k in sorted(fr.keys()):
            lines.append(f"{k} & {fr[k]}\\\\ \hline")
        lines.append(r"\end{tabular}")
        lines.append(r"\caption{명시적 실패/경계 사례 라벨 분포}")
        lines.append(r"\label{tab:chem_external_inspection_fail_reasons}")
        lines.append(r"\end{table}")

    return "\n".join(lines) + "\n"


# ----------------------------
# Gate report helpers
# ----------------------------

def make_gate_report(
    gate_id: str,
    status: str,
    checks: List[dict],
    inputs: dict,
    outputs: dict,
    generator: str,
    created: str,
    notes: str = "",
) -> dict:
    ts = f"{created}T00:00:00Z" if created else ""
    return {
        "gate_id": gate_id,
        "status": status,
        "created": created,
        "result": status,
        "fail_labels": [] if status == "PASS" else ["CHECK_FAILED"],
        "checks": checks,
        "inputs": inputs,
        "outputs": outputs,
        "generated_by": generator,
        "notes": notes,
        "timestamp_utc": ts,
    }


# ----------------------------
# Main
# ----------------------------

def main() -> int:
    script_path = Path(__file__).resolve()
    vp_root = script_path.parents[1]  # 04_vp_whitepaper/
    bundle_root = vp_root.parents[0]  # AQD_DOI_bundle_unified...

    created_date = protocol_created(bundle_root)
    stamp_utc = f"{created_date}T00:00:00Z" if created_date else ""

    lock_path = vp_root / "LOCK" / "chem_external_inspection_lock.json"
    lock = load_json(lock_path)

    data_path = bundle_root / lock["inputs"]["external_inspection_csv"]
    rows = read_csv_allow_comments(data_path)
    if not rows:
        raise SystemExit(f"No rows found in {data_path}")

    r_vac = float(lock["constants"]["r_vac_fm"])
    tol_pct = float(lock["constants"]["gate_tolerance_pct"])

    # Required columns
    required_cols = [
        "ID",
        "GROUP",
        "FORMULA",
        "P_IDX",
        "CALC_AMP(fm)",
        "OBS_REF_AMP(fm)",
        "ERROR(%)",
        "SOURCE_REF",
        "STATUS",
    ]
    for c in required_cols:
        if c not in rows[0]:
            raise SystemExit(f"Missing column '{c}' in {data_path}")

    # Deterministic processing
    processed: List[dict] = []
    check_failures: List[dict] = []

    # The dataset stores rounded decimal columns (typically 2 decimals for amplitudes
    # and 4 decimals for P_IDX). A small rounding discrepancy is therefore expected.
    AMP_TOL_FM = 0.10   # rounding tolerance for fm columns
    ERR_TOL_PCT = 0.10  # rounding tolerance for error column

    for r in rows:
        rid = r["ID"]
        group = r["GROUP"]
        formula = r["FORMULA"]

        p_idx = float(r["P_IDX"])
        calc_amp_reported = float(r["CALC_AMP(fm)"])
        obs_amp = float(r["OBS_REF_AMP(fm)"])
        err_reported = float(r["ERROR(%)"])
        status_raw = r["STATUS"].strip()

        # Recompute
        calc_amp = r_vac / math.sqrt(p_idx)
        err = 100.0 * (calc_amp - obs_amp) / obs_amp

        # Integrity checks
        if abs(calc_amp - calc_amp_reported) > AMP_TOL_FM:
            check_failures.append({
                "id": rid,
                "check": "calc_amp",
                "got": calc_amp_reported,
                "expected": calc_amp,
                "abs_err": abs(calc_amp_reported - calc_amp),
                "tol": AMP_TOL_FM,
            })

        if abs(err - err_reported) > ERR_TOL_PCT:
            check_failures.append({
                "id": rid,
                "check": "error_pct",
                "got": err_reported,
                "expected": err,
                "abs_err": abs(err_reported - err),
                "tol": ERR_TOL_PCT,
            })

        is_pass_expected = abs(err) <= tol_pct
        is_pass_reported = status_raw.upper().startswith("PASS")
        if is_pass_expected != is_pass_reported:
            check_failures.append({
                "id": rid,
                "check": "status",
                "got": status_raw,
                "expected": "PASS" if is_pass_expected else "FAIL*",
                "abs_err": None,
                "tol": f"±{tol_pct}%",
            })

        processed.append({
            "id": rid,
            "group": group,
            "formula": formula,
            "p_idx": p_idx,
            "calc_amp_fm": calc_amp_reported,
            "calc_amp_fm_recomputed": calc_amp,
            "obs_amp_fm": obs_amp,
            "error_pct": err_reported,
            "error_pct_recomputed": err,
            "source_ref": r.get("SOURCE_REF", ""),
            "status": status_raw,
        })

    # Summary stats
    total_n = len(processed)
    pass_n = sum(1 for r in processed if r["status"].upper().startswith("PASS"))
    fail_n = total_n - pass_n

    group_stats: Dict[str, dict] = {}
    for r in processed:
        g = r["group"]
        gs = group_stats.setdefault(g, {"n": 0, "pass": 0, "fail": 0})
        gs["n"] += 1
        if r["status"].upper().startswith("PASS"):
            gs["pass"] += 1
        else:
            gs["fail"] += 1

    for g, gs in group_stats.items():
        gs["pass_rate_pct"] = 100.0 * gs["pass"] / gs["n"] if gs["n"] else 0.0

    # Failure reason distribution
    failure_reasons: Dict[str, int] = {}
    for r in processed:
        st = r["status"].strip()
        if st.upper().startswith("PASS"):
            continue
        # Normalize reason label: FAIL or FAIL_* suffix
        if "_" in st:
            reason = st
        else:
            reason = "FAIL"
        failure_reasons[reason] = failure_reasons.get(reason, 0) + 1

    # Top absolute errors
    top_abs_errors = sorted(processed, key=lambda x: abs(x["error_pct_recomputed"]), reverse=True)[:15]
    top_abs_errors_slim = [
        {
            "id": r["id"],
            "group": r["group"],
            "formula": r["formula"],
            "calc_amp_fm": round(r["calc_amp_fm_recomputed"], 3),
            "obs_amp_fm": r["obs_amp_fm"],
            "error_pct": round(r["error_pct_recomputed"], 3),
            "status": r["status"],
        }
        for r in top_abs_errors
    ]

    summary = {
        "lock": lock["version"],
        "generated_utc": stamp_utc,
        "dataset": {
            "path": str(lock["inputs"]["external_inspection_csv"]),
            "sha256": sha256_file(data_path),
            "n_rows": total_n,
        },
        "r_vac_fm": r_vac,
        "gate_tolerance_pct": tol_pct,
        "total": {
            "n": total_n,
            "pass": pass_n,
            "fail": fail_n,
            "pass_rate_pct": 100.0 * pass_n / total_n if total_n else 0.0,
        },
        "group_stats": group_stats,
        "failure_reasons": failure_reasons,
        "top_abs_errors": top_abs_errors_slim,
        "integrity_mismatches": {
            "n": len(check_failures),
            "examples": check_failures[:20],
        },
    }

    outdir = vp_root / "outputs" / "chem"
    outdir.mkdir(parents=True, exist_ok=True)

    rows_json_path = outdir / "external_inspection_rows.json"
    write_json(rows_json_path, {
        "lock": lock["version"],
        "generated_utc": stamp_utc,
        "rows": processed,
    })

    summary_json_path = outdir / "external_inspection_summary.json"
    write_json(summary_json_path, summary)

    tex_path = outdir / "table_external_inspection_summary.tex"
    tex_path.write_text(latex_table_summary(summary), encoding='utf-8')

    # Run bundle (checksums)
    run_dir = vp_root / "runs" / "run_CHEM_EXT_INSPECTION_0001"
    run_dir.mkdir(parents=True, exist_ok=True)
    write_json(run_dir / "run_meta.json", {
        "lock": lock["version"],
        "generated_utc": stamp_utc,
        "dataset_sha256": sha256_file(data_path),
        "n_rows": total_n,
    })
    write_json(run_dir / "checksums.json", {
        str(data_path.relative_to(bundle_root)): sha256_file(data_path),
        str(rows_json_path.relative_to(bundle_root)): sha256_file(rows_json_path),
        str(summary_json_path.relative_to(bundle_root)): sha256_file(summary_json_path),
        str(tex_path.relative_to(bundle_root)): sha256_file(tex_path),
    })

    # Gate report
    gate_id = "G-CHEM-EXT-INSPECTION-INTEGRITY"
    status = "PASS" if len(check_failures) == 0 else "FAIL"

    gate_checks = [{
        "name": "integrity_mismatch_count",
        "got": len(check_failures),
        "expected": 0,
        "pass": len(check_failures) == 0,
    }]

    # Always record dataset statistics in the gate report (even if PASS)
    gate_checks.append({
        "name": "dataset_row_count",
        "got": total_n,
        "expected": total_n,
        "pass": True,
    })

    gate_report = make_gate_report(
        gate_id=gate_id,
        status=status,
        checks=gate_checks,
        inputs={
            "lock": str(lock_path.relative_to(bundle_root)),
            "dataset": str(data_path.relative_to(bundle_root)),
        },
        outputs={
            "summary_json": str(summary_json_path.relative_to(bundle_root)),
            "summary_tex": str(tex_path.relative_to(bundle_root)),
        },
        generator="04_vp_whitepaper/scripts/run_chem_external_inspection.py",
        created=created_date,
        notes="Integrity gate for DOI-embedded external inspection dataset. Fails indicate internal inconsistency, not chemical model failure.",
    )

    gate_path = bundle_root / "gate" / "reports" / "gate_report_chem_external_inspection.json"
    write_json(gate_path, gate_report)

    return 0 if status == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
