#!/usr/bin/env python3
"""Geometry-classified dilution bounds check (Sec.18.2.6).

Motivation
----------
In Step7 chemistry, some polyatomic species use a dilution/geometry rule
("Rule B") in addition to stoichiometric averaging (Rule A). To defend against
"arbitrary selection" criticism, this script:

- locks a small geometry classifier for representative molecules (CH4/H2O/NH3),
- locks conservative geometry-dependent upper bounds for phi_eff,
- mechanically checks that the Step7 dataset implies phi_eff values within bounds.

Definitions
-----------
P_avg_atom = stoichiometry-weighted average of atomic P_idx values
phi_eff   = P_idx(molecule) / P_avg_atom

Gate rule
---------
phi_eff <= phi_eff_upper(geometry) + tol

Outputs
-------
- 04_vp_whitepaper/outputs/chem/geometry_phi_bounds_check.json
- 04_vp_whitepaper/outputs/chem/table_geometry_phi_bounds.tex
- gate/reports/gate_report_CHEM_GEOMETRY_PHI_BOUNDS.json

No third-party dependencies.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import math
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding='utf-8')


def protocol_created(bundle_root: Path) -> str:
    p = bundle_root / "registry" / "protocol_lock.json"
    if p.exists():
        try:
            v = load_json(p).get("created")
            if v:
                return str(v)
        except Exception:
            pass
    return str(date.today())


def read_csv_dicts_allow_comments(path: Path) -> List[dict]:
    lines: List[str] = []
    for ln in path.read_text(encoding='utf-8').splitlines():
        s = ln.strip()
        if not s:
            continue
        if s.startswith('#'):
            continue
        lines.append(ln)
    # Find header start
    header_i = None
    for i, ln in enumerate(lines):
        if ln.startswith('ID,'):
            header_i = i
            break
    if header_i is None:
        raise RuntimeError("CSV header not found")
    reader = csv.DictReader(io.StringIO("\n".join(lines[header_i:])))
    out: List[dict] = []
    for r in reader:
        if not r.get('ID') or str(r['ID']).startswith('#'):
            continue
        out.append({k.strip(): (v.strip() if isinstance(v, str) else v) for k, v in r.items()})
    return out


FORMULA_RE = re.compile(r"([A-Z][a-z]?)(\d*)")


def parse_formula(formula: str) -> Dict[str, int]:
    """Parse a simple chemical formula like CH4 or H2O into element counts.

    This parser supports only flat formulas without parentheses.
    """
    formula = formula.strip()
    if not formula:
        raise ValueError("empty formula")
    counts: Dict[str, int] = {}
    for elem, n_str in FORMULA_RE.findall(formula):
        n = int(n_str) if n_str else 1
        counts[elem] = counts.get(elem, 0) + n
    if not counts:
        raise ValueError(f"could not parse formula: {formula}")
    return counts


@dataclass
class RowCheck:
    species: str
    geometry: str
    P_idx_mol: float
    P_avg_atom: float
    phi_eff: float
    phi_upper: float
    margin: float
    status: str
    row_id: Optional[str] = None


def latex_table(checks: List[RowCheck], tol: float) -> str:
    lines: List[str] = []
    lines.append(r"% Auto-generated by 04_vp_whitepaper/scripts/run_chem_geometry_phi.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\begin{tabular}{|l|l|c|c|c|c|}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Species} & \textbf{Geometry} & $P_{idx}$ & $P_{avg}$ & $\phi_{eff}$ & Status\\ \hline")

    for c in checks:
        lines.append(
            f"{c.species} & {c.geometry} & {c.P_idx_mol:.4f} & {c.P_avg_atom:.4f} & {c.phi_eff:.4f} & {c.status}\\ \\hline"
        )

    lines.append(r"\end{tabular}")
    lines.append(rf"\caption{{Geometry-classified dilution bounds (LOCK). Definition: $\phi_{{eff}}=P_{{idx}}(mol)/P_{{avg}}$. Gate: $\phi_{{eff}}\le\phi_{{upper}}(geom)+{tol:g}$.}}")
    lines.append(r"\label{tab:chem_geometry_phi_bounds}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def main() -> int:
    bundle_root = Path(__file__).resolve().parents[2]
    created = protocol_created(bundle_root)

    lock_path = bundle_root / "04_vp_whitepaper" / "LOCK" / "chem_geometry_phi_lock.json"
    lock = load_json(lock_path)

    csv_path = bundle_root / lock["inputs"]["external_inspection_csv"]
    rows = read_csv_dicts_allow_comments(csv_path)

    tol = float(lock["constants"]["tolerances"]["phi_eff_abs"])
    target = list(lock["constants"]["target_species"])
    classifier = dict(lock["constants"]["classifier"])

    # Geometry bounds
    geo_bounds = {}
    for g, obj in lock["constants"]["geometry_phi_eff_upper"].items():
        geo_bounds[g] = float(obj["value"])

    # Atomic P_idx map
    atom_pidx: Dict[str, float] = {}
    for r in rows:
        if r.get("GROUP") == "Atom":
            atom_pidx[str(r["FORMULA"]).strip()] = float(r["P_IDX"])

    if not atom_pidx:
        raise RuntimeError("No atomic rows found in dataset")

    # Index dataset rows by formula
    by_formula: Dict[str, dict] = {}
    for r in rows:
        f = str(r.get("FORMULA", "")).strip()
        if f:
            by_formula.setdefault(f, r)

    checks: List[RowCheck] = []
    ok = True

    for sp in target:
        if sp not in by_formula:
            ok = False
            checks.append(RowCheck(
                species=sp,
                geometry=classifier.get(sp, "UNKNOWN"),
                P_idx_mol=float('nan'),
                P_avg_atom=float('nan'),
                phi_eff=float('nan'),
                phi_upper=float('nan'),
                margin=float('nan'),
                status="FAIL",
                row_id=None,
            ))
            continue

        row = by_formula[sp]
        P_idx_mol = float(row["P_IDX"])

        # Stoichiometric P_avg from atomic P_idx
        counts = parse_formula(sp)
        total = sum(counts.values())
        p_sum = 0.0
        missing: List[str] = []
        for elem, n in counts.items():
            if elem not in atom_pidx:
                missing.append(elem)
                continue
            p_sum += n * atom_pidx[elem]
        if missing:
            raise RuntimeError(f"Missing atomic P_idx for: {missing}")

        P_avg_atom = p_sum / total
        phi_eff = P_idx_mol / P_avg_atom

        geom = classifier.get(sp)
        if geom is None:
            ok = False
            checks.append(RowCheck(
                species=sp,
                geometry="UNCLASSIFIED",
                P_idx_mol=P_idx_mol,
                P_avg_atom=P_avg_atom,
                phi_eff=phi_eff,
                phi_upper=float('nan'),
                margin=float('nan'),
                status="FAIL",
                row_id=row.get("ID"),
            ))
            continue

        if geom not in geo_bounds:
            raise RuntimeError(f"No bound defined for geometry class: {geom}")

        phi_upper = geo_bounds[geom]
        margin = phi_upper - phi_eff
        status = "PASS" if phi_eff <= (phi_upper + tol) else "FAIL"
        ok = ok and (status == "PASS")

        checks.append(RowCheck(
            species=sp,
            geometry=geom,
            P_idx_mol=P_idx_mol,
            P_avg_atom=P_avg_atom,
            phi_eff=phi_eff,
            phi_upper=phi_upper,
            margin=margin,
            status=status,
            row_id=row.get("ID"),
        ))

    overall = "PASS" if ok else "FAIL"

    # Write outputs
    out_json = bundle_root / "04_vp_whitepaper" / "outputs" / "chem" / "geometry_phi_bounds_check.json"
    out_tex = bundle_root / "04_vp_whitepaper" / "outputs" / "chem" / "table_geometry_phi_bounds.tex"

    write_json(out_json, {
        "DATA_SPEC_ID": "VP_CHEM_GEOMETRY_PHI_BOUNDS_V1",
        "created": created,
        "status": overall,
        "inputs": {
            "lock": str(lock_path.relative_to(bundle_root)),
            "dataset": str(csv_path.relative_to(bundle_root)),
        },
        "checks": [c.__dict__ for c in checks],
    })

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(latex_table(checks, tol), encoding='utf-8')

    # Gate report
    gate = {
        "gate_id": "G-CHEM-GEOMETRY-PHI-BOUNDS",
        "status": overall,
        "created": created,
        "evidence": {
            "lock_sha256": sha256_file(lock_path),
            "dataset_sha256": sha256_file(csv_path),
            "output_json_sha256": sha256_file(out_json),
            "generated_by": str(Path(__file__).relative_to(bundle_root)),
        },
        "checks": [c.__dict__ for c in checks],
    }

    gate_path = bundle_root / "gate" / "reports" / "gate_report_CHEM_GEOMETRY_PHI_BOUNDS.json"
    write_json(gate_path, gate)

    print(f"[OK] wrote {out_json.relative_to(bundle_root)}")
    print(f"[OK] wrote {out_tex.relative_to(bundle_root)}")
    print(f"[OK] wrote {gate_path.relative_to(bundle_root)} (status={overall})")

    return 0 if overall == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
