#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_docs.py  --  Cardiorespiratory WRITING phase: per-title canonical SEO HTML generator.

HARD RULE: refuses while gates.writing_locked() is True -- until research is signed off
(reports/research_complete.json all_green) AND PHASE=="writing". Research first, writing second.

WHEN UNLOCKED, emits the canonical site per VP-SPEC v1.8 (full spec at ../VP_SPEC_v1_8.md):
  * CANONICAL artifact = HTML in docs/ (C2). All math is inline Unicode text (spec 7A); no
    display-equation SVGs, so the page set is self-contained (no render pipeline, no bundled TeX)
    and the Phase-1 "display-eq count == svg count" check is trivially 0==0.
  * ONE HTML PAGE PER SECTION (C4 / section 6): answer-first <p class="answer"> (40-60 words),
    self-contained, JSON-LD ScholarlyArticle + BreadcrumbList, canonical, claim-strip
    (grade + GitHub repro + DOI), one vp-card per cited locked quantity (6-R.2).
  * BODY in English (C0); honest grades [F]/[V]/[H]/[L]/[O] with stated obstacles (C3);
    every number regenerated by the engine (C1).
  * Output under docs/: cardioresp_vp_site/<slug>/index.html, cardioresp_vp_site/index.html hub,
    cardioresp_vp_site/_meta.json, top index.html, sitemap.xml, robots.txt (7 bots), llms.txt,
    assets/css/site.css. Slugs by the section-3 algorithm. manifest populated.
"""
import os, sys, json, re, html, datetime
import importlib

_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG  = os.path.abspath(os.path.join(_HERE, ".."))
_DOCS = os.path.join(_PKG, "docs")
_MANI = os.path.join(_PKG, "manifest", "cardioresp_vp_site.csv")
for p in (os.path.join(_PKG, "repro", "_engine"),
          os.path.join(_PKG, "repro", "_verify"),
          os.path.join(_PKG, "repro", "_oncology"),
          os.path.join(_PKG, "inherited")):
    sys.path.insert(0, p)
gates = importlib.import_module("gates")

# --------------------------------------------------------------------------- identity
PAPER_ID = "cardioresp_vp_site"
CODE     = "car"
SHORT    = "Cardiorespiratory VP"
TITLE    = ("Cardiorespiratory Emergence: Heart and Lung as Coupled Relaxation "
            "Oscillators under Reflex Control")
AUTHOR   = "Young Jae Lee"
ORCID    = "https://orcid.org/0009-0002-7535-8245"
DOMAIN   = "https://jamming-physics.org"
REPO     = "https://github.com/rego093-sketch/jamming-physics"
LICENSE  = "https://creativecommons.org/licenses/by/4.0/"
DOI         = "10.5281/zenodo.20755371"          # concept DOI (Zenodo), issued for cardioresp_vp_site
DOI_URL     = "https://doi.org/" + DOI
DOI_PENDING = False                              # archived: the concept DOI above is now live
RELEASE_DATE = "2026-06-18"                       # PINNED: build output must not depend on wall-clock (C1 determinism)
BUILD_DATE  = RELEASE_DATE
SITE_NAME   = "Jamming Physics"

# Standing discovery keywords (entity-rich; the canonical surface competes by retrieval, not by a journal).
KEYWORDS_BASE = [
    "jamming physics", "VP theory", "vacuum physics", "first-principles emergence",
    "DNA emergence", "master gene", "gene clock", "stacking stability", "NKX2-5", "NKX2-1",
    "FitzHugh-Nagumo", "relaxation oscillator", "R19 bistable switch", "cardiac pacemaker",
    "preBotzinger complex", "respiratory rhythm", "cardiorespiratory coupling",
    "chemoreflex loop gain", "periodic breathing", "apnea threshold",
    "respiratory sinus arrhythmia", "heart rate variability", "Cheyne-Stokes respiration",
    "baroreflex", "carcinogen dose-response", "linear no-threshold", "Kramers escape",
    "deterministic reproducibility", "falsifiable model", "Young Jae Lee",
]

STOPWORDS = {"the","a","an","of","and","as","its","for","to","in","on","with","from"}

def slugify(title, number):
    s = title.lower().encode("ascii","ignore").decode("ascii")
    s = re.sub(r"[^a-z0-9]+","-",s).strip("-")
    words = [w for w in s.split("-") if w and w not in STOPWORDS][:5]
    return "%02d-%s" % (number, "-".join(words))

def seo_meta(title_text, desc_text, url, og_type="article", extra_keywords=None):
    """Discovery meta block shared by every page type: keywords, author, robots, Open Graph, Twitter.
    Deterministic (no wall-clock); attributes are HTML-escaped; conclusion-first description supplied by caller."""
    kws = list(KEYWORDS_BASE)
    for k in (extra_keywords or []):
        kp = html.unescape(re.sub("<[^>]+>", "", k)).strip()
        if kp and kp not in kws:
            kws.append(kp)
    kw = html.escape(", ".join(kws))
    t  = html.escape(title_text)
    d  = html.escape(desc_text)
    u  = html.escape(url)
    return (
        '<meta name="keywords" content="' + kw + '">\n'
        '<meta name="author" content="' + html.escape(AUTHOR) + '">\n'
        '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">\n'
        '<meta property="og:type" content="' + og_type + '">\n'
        '<meta property="og:site_name" content="' + html.escape(SITE_NAME) + '">\n'
        '<meta property="og:locale" content="en_US">\n'
        '<meta property="og:title" content="' + t + '">\n'
        '<meta property="og:description" content="' + d + '">\n'
        '<meta property="og:url" content="' + u + '">\n'
        '<meta name="twitter:card" content="summary">\n'
        '<meta name="twitter:title" content="' + t + '">\n'
        '<meta name="twitter:description" content="' + d + '">\n')

# --------------------------------------------------------------------------- numbers (C1)
def gather():
    eng = importlib.import_module("vp_car_engine")
    st  = importlib.import_module("stress_tests")
    onc = importlib.import_module("carcinogen_dose_response")
    raw, sha = eng.emit(eng.circulate())
    dyn = json.loads(raw)
    batt = st.run_battery()
    onco = onc.results()
    organs = {o["organ"]: o for o in dyn["organs"]["organs"]}
    ta = dyn["dynamics"]["time_anchor"]
    D = dict(
        sha=sha, onco=onco,
        order_asc=dyn["organs"]["gamma_order_ascending"],
        kappa=ta["kappa_s_per_arb"], resting_hz=ta["resting_hr_hz"],
        resting_bpm=round(ta["resting_hr_hz"]*60.0),
        g_heart=organs["heart"]["gamma"], g_lung=organs["lung"]["gamma"],
        sp_heart=round(organs["heart"]["functional_spinodal"],6),
        sp_lung=round(organs["lung"]["functional_spinodal"],6),
        tau_heart=dyn["oscillators"]["heart"]["tau_s"],
        tau_lung=dyn["oscillators"]["lung"]["tau_s"],
        beats_heart=dyn["oscillators"]["heart"]["beats"],
        beats_lung=dyn["oscillators"]["lung"]["beats"],
        eupnea_bpm=dyn["dynamics"]["eupnea"]["breaths_per_min"],
        ratio_bb=dyn["dynamics"]["eupnea"]["ratio_breath_to_beat"],
        chemo_LGc=dyn["dynamics"]["chemoreflex"]["LG_c"],
        chemo_T=dyn["dynamics"]["chemoreflex"]["unstable_period_s"],
        rsa_fresp=dyn["dynamics"]["rsa"]["f_resp_hz"],
        rsa_peak=dyn["dynamics"]["rsa"]["hrv_peak_hz"],
        csr_slope=dyn["dynamics"]["cheyne_stokes"]["period_vs_delay_slope"],
        baro_slope=dyn["dynamics"]["baroreflex"]["static_slope_bpm_per_mmHg"],
        baro_lat=dyn["dynamics"]["baroreflex"]["onset_latency_s"],
        spq_lung=round(onco["spinodal"],6),
        B0_lung=round(onco["gamma_lung_NKX2_1"]**2/4.0,6),
        rr=onco["RR_curve"], rr_tiny=onco["lnt"]["rr_at_tiny_dose"],
        rr_slope0=onco["lnt"]["barrier_drop_slope_at_origin"],
        syn_ratio=onco["synergy"]["combined_over_product"],
        syn_regime=onco["synergy"]["regime"],
    )
    return D

# --------------------------------------------------------------------------- small helpers
def m(x):                       # inline math span (counted as eq_inline)
    return '<span class="m">%s</span>' % x
def tbl(headers, rows):
    h = "".join("<th>%s</th>" % html.escape(str(c)) for c in headers)
    body = ""
    for r in rows:
        body += "<tr>" + "".join("<td>%s</td>" % c for c in r) + "</tr>"
    return '<table><thead><tr>%s</tr></thead><tbody>%s</tbody></table>' % (h, body)

GRADE_CLASS = {"[F]":"g-forced","[V]":"g-verified","[H]":"g-hypothesis",
               "[L]":"g-calibrated","[O]":"g-open"}
GRADE_WORD  = {"[F]":"forced","[V]":"verified","[H]":"hypothesis",
               "[L]":"calibrated (literature-anchored)","[O]":"open"}
GRADE_PRIORITY = ["[F]","[V]","[H]","[L]","[O]"]

def page_grade(tokens):
    if not tokens: return None
    from collections import Counter
    c = Counter(tokens)
    best = max(c.values())
    tied = [t for t in GRADE_PRIORITY if c.get(t,0) == best]
    return tied[0] if tied else None

def card(locked_id, value, meaning, grade, href, anchor_text):
    return ('<aside class="vp-card" data-locked="%s"><b>%s</b> &mdash; %s '
            '<b>%s</b> %s. <a href="%s" rel="noopener">%s</a></aside>'
            % (locked_id, value, meaning, grade, GRADE_WORD[grade], href, anchor_text))

# Reusable cards (cited locked quantities) -----------------------------------
def cards_lib(D):
    return {
        "gamma_heart": card("gamma-nkx2-5", "&gamma;(NKX2-5) = %.4g" % D["g_heart"],
            "measured stacking-stability of the heart master gene from the 4D-DNA gene-clock; sets the SA-node R19 switch (measured input, never fitted here)",
            "[V]", "/dna/", "canonical: 4D-DNA gene-clock"),
        "gamma_lung": card("gamma-nkx2-1", "&gamma;(NKX2-1) = %.4g" % D["g_lung"],
            "measured stacking-stability of the lung master gene from the 4D-DNA gene-clock; sets the preBotzinger R19 switch (measured input, never fitted here)",
            "[V]", "/dna/", "canonical: 4D-DNA gene-clock"),
        "order": card("dev-order", "order = argsort(&gamma;)",
            "developmental/emergence order is the ascending-&gamma; readout (lung &rarr; heart); identity and order are owned by the DNA gene-clock and read out here, not refitted",
            "[V]", "/dna/", "canonical: 4D-DNA gene-clock"),
        "resting_hr": card("resting-hr", "resting HR = %.2f Hz (%d bpm)" % (D["resting_hz"], D["resting_bpm"]),
            "the single physiological time anchor; cited resting heart rate (Task Force 1996; Jose &amp; Collison 1970)",
            "[L]", "/cardioresp_vp_site/03-eupnea-period-shared-oscillator/", "used as the rate anchor"),
        "kappa": card("kappa-anchor", "&kappa; = %.5g s/arb" % D["kappa"],
            "the single time-to-seconds conversion, fixed once by setting the heart's intrinsic relaxation rhythm equal to the cited resting rate; every physical rate is then a model rate divided by &kappa;",
            "[L]", "/cardioresp_vp_site/03-eupnea-period-shared-oscillator/", "derivation of the time anchor"),
        "hf_band": card("hf-hrv-band", "HF-HRV band = 0.15&ndash;0.40 Hz",
            "vagally mediated high-frequency heart-rate-variability band; the respiratory-sinus-arrhythmia window (Task Force 1996)",
            "[L]", "/cardioresp_vp_site/05-respiratory-sinus-arrhythmia/", "used as the RSA lock window"),
        "fhn": card("fhn-oscillator", "FitzHugh&ndash;Nagumo (R19 cubic)",
            "the shared relaxation-oscillator law &mdash; fast excitable variable with the R19 cubic nonlinearity plus a slow recovery variable; the same bistable switch used across the VP program",
            "[F]", "/physics/", "canonical: jamming-lattice substrate"),
        "r19_barrier": card("r19-barrier", "B = &gamma;&sup2;/4",
            "the R19 bistable-switch energy barrier between the two basins (substrate primitive)",
            "[F]", "/physics/", "canonical: jamming-lattice substrate"),
        "spinodal": card("spinodal", "h* = 2(&gamma;/3)^1.5",
            "the bias past which one R19 basin disappears and the flip becomes discontinuous (substrate primitive)",
            "[F]", "/physics/", "canonical: jamming-lattice substrate"),
        "loop_gain": card("critical-loop-gain", "LG / LG<sub>c</sub> = 1",
            "the Hopf-bifurcation onset of the delayed chemoreflex: below it ventilation is steady, above it periodic breathing self-sustains (reported relative to its own critical value)",
            "[V]", "/cardioresp_vp_site/04-apnea-threshold-chemoreflex-loop-gain/", "derivation of the apnea threshold"),
    }

# --------------------------------------------------------------------------- section content
def build_sections(D):
    C = cards_lib(D)
    rr = {p["pack_years"]: p["RR"] for p in D["rr"]}
    S = []

    # ---- 1 overview ----
    body = (
        "<h2>One substrate, two organs, one oscillator</h2>"
        "<p>The heart and the lung are emerged here from their measured master-gene stacking "
        "stabilities &gamma;, not assigned by hand. The cardiac switch follows " + m("&gamma;(NKX2-5) = %.4g" % D["g_heart"]) +
        " and the respiratory switch follows " + m("&gamma;(NKX2-1) = %.4g" % D["g_lung"]) + ", both read from the "
        "DNA gene-clock and never refitted here.</p>"
        "<p>Both organs are the SAME FitzHugh&ndash;Nagumo relaxation oscillator from the shared substrate; only the "
        "slow recovery time &tau;<sub>s</sub> differs (heart " + m("&tau;<sub>s</sub> = %g" % D["tau_heart"]) +
        ", lung " + m("&tau;<sub>s</sub> = %g" % D["tau_lung"]) + "). The longer the recovery, the slower the rhythm, "
        "so the heart runs fast and the lung runs slow on one mechanism.</p>"
        "<p>On that DNA-anchored oscillator this volume derives the full functional dynamics: it sets a single "
        "physiological time anchor, then derives breathing rate, the apnea (periodic-breathing) threshold, respiratory "
        "sinus arrhythmia, the Cheyne&ndash;Stokes period, and baroreflex regulation &mdash; plus a shared R19 oncology "
        "kernel for carcinogen dose&ndash;response.</p>"
        "<h2>Developmental order is a pure &gamma; readout</h2>"
        "<p>Ordering the two organs by ascending &gamma; gives " + m("%s &rarr; %s" % (D["order_asc"][0], D["order_asc"][1])) +
        ". The identity and the developmental order are established results of the DNA gene-clock, read out here "
        "exactly; on that DNA-anchored foundation this volume derives the full functional dynamics. The complete "
        "emergence chain &mdash; gene &rarr; &gamma; &rarr; R19 switch &rarr; oscillator &mdash; is set out in "
        "<a href=\"/" + PAPER_ID + "/10-dna-master-genes-stacking-stability/\">&sect;10</a>.</p>"
        "<h2>What is forced, anchored, and open</h2>"
        + tbl(["target","result","grade"],
              [["T1 eupnea period", "%.2f breaths/min (ratio %.3f of beat)" % (D["eupnea_bpm"], D["ratio_bb"]), "[V] ratio / [L] rate"],
               ["T2 apnea threshold", "periodic breathing onsets at loop gain &asymp; 1", "[V]"],
               ["T3 RSA", "HF-HRV peak locks to f<sub>resp</sub> only when coupled", "[V]"],
               ["T4 Cheyne&ndash;Stokes", "period &asymp; 2 &times; circulatory delay", "[V]"],
               ["T5 baroreflex", "%g bpm/mmHg, regulates to setpoint" % D["baro_slope"], "[L]"],
               ["oncology", "RR(0)=1, no threshold, convex shape", "[F]/[V]; absolute [O]"]])
        + "<p>Every number on every page is regenerated by the deterministic engine and verified by a "
        "two-run identical-sha256 check; the stress battery must be green before this site can be written.</p>"
    )
    S.append(dict(no=1, title="Cardiorespiratory Emergence Overview",
        short="Overview", grade_tokens=["[V]","[V]","[V]","[V]","[L]","[F]"],
        answer=("Heart and lung emerge from their measured master-gene stacking stabilities and turn out to be the "
                "same FitzHugh&ndash;Nagumo relaxation oscillator, differing only in recovery time. From one cited "
                "time anchor the model derives breathing rate, the apnea threshold, respiratory sinus arrhythmia, the "
                "Cheyne&ndash;Stokes period, baroreflex regulation, and a shared carcinogen dose&ndash;response kernel."),
        abstract=("Heart (NKX2-5) and lung (NKX2-1) are emerged from measured &gamma; and share one relaxation "
                  "oscillator, separated only by &tau;<sub>s</sub> (%g vs %g). Resting HR = %.2f Hz anchors time; "
                  "five reflex/coupling targets and an R19 oncology kernel follow." % (D["tau_heart"], D["tau_lung"], D["resting_hz"])),
        cards=[C["gamma_heart"], C["gamma_lung"], C["resting_hr"]], body=body,
        keys=["&gamma;(NKX2-5) = %.4g" % D["g_heart"], "&gamma;(NKX2-1) = %.4g" % D["g_lung"]]))

    # ---- 2 oscillator ----
    body = (
        "<h2>The shared relaxation oscillator</h2>"
        "<p>Both pacemakers are one FitzHugh&ndash;Nagumo unit: a fast excitable variable s with cubic nonlinearity and "
        "a slow recovery variable w, " + m("ds/dt = (E(&gamma;s &minus; s&sup3;) &minus; I w + drive)/&tau;<sub>f</sub>") +
        ", " + m("dw/dt = (s &minus; &beta;w)/&tau;<sub>s</sub>") + ". The cubic is the same R19 bistable form used "
        "everywhere in this program; nothing organ-specific is added beyond &gamma; and &tau;<sub>s</sub>.</p>"
        "<p>The slow recovery time sets the rhythm: larger &tau;<sub>s</sub> means a slower relaxation cycle. The heart "
        "uses " + m("&tau;<sub>s</sub> = %g" % D["tau_heart"]) + " and the lung " + m("&tau;<sub>s</sub> = %g" % D["tau_lung"]) +
        ", which is precisely why one mechanism yields a fast cardiac beat and a slow respiratory cycle.</p>"
        "<h2>Both organs oscillate</h2>"
        "<p>Run free, each unit produces a sustained limit cycle rather than a fixed point. Over a fixed window the heart "
        "completes " + m("%d" % D["beats_heart"]) + " cycles and the lung " + m("%d" % D["beats_lung"]) + ", the expected "
        "fast/slow split.</p>"
        + tbl(["organ","master gene","&gamma;","&tau;<sub>s</sub>","class","role"],
              [["heart","NKX2-5","%.4g"%D["g_heart"],"%g"%D["tau_heart"],"oscillator","SA-node pacemaker + conduction + contraction"],
               ["lung","NKX2-1","%.4g"%D["g_lung"],"%g"%D["tau_lung"],"oscillator","preBotzinger inspiratory rhythm + ventilatory pump"]])
        + "<h2>Grade</h2>"
        "<p>The oscillator mechanism is verified [V] from the shared substrate; the absolute rate is set by the cited "
        "anchor, not emergent, and is treated separately in the next section.</p>"
    )
    S.append(dict(no=2, title="Heart and Lung as a Relaxation Oscillator",
        short="Shared oscillator", grade_tokens=["[V]"],
        answer=("Heart and lung are the same FitzHugh&ndash;Nagumo relaxation oscillator built on the R19 cubic switch. "
                "Only the slow recovery time &tau;<sub>s</sub> differs &mdash; %g for the heart, %g for the lung &mdash; so "
                "one mechanism produces a fast cardiac beat and a slow respiratory cycle. Both run as sustained limit "
                "cycles; the mechanism is grade [V]." % (D["tau_heart"], D["tau_lung"])),
        abstract=("One FitzHugh&ndash;Nagumo unit, " + m("ds/dt = (E(&gamma;s&minus;s&sup3;)&minus;Iw+drive)/&tau;<sub>f</sub>") +
                  ", serves both organs; only &tau;<sub>s</sub> (%g heart, %g lung) sets the rhythm. Larger &tau;<sub>s</sub> "
                  "&rarr; slower cycle. [V]." % (D["tau_heart"], D["tau_lung"])),
        cards=[C["gamma_heart"], C["gamma_lung"], C["r19_barrier"]], body=body,
        keys=["&tau;<sub>s</sub> heart = %g" % D["tau_heart"], "&tau;<sub>s</sub> lung = %g" % D["tau_lung"]]))

    # ---- 3 eupnea ----
    sw = D["onco"]  # placeholder to keep linter calm
    body = (
        "<h2>One time anchor fixes the clock</h2>"
        "<p>A single conversion &kappa; from model time to seconds is fixed by declaring the heart's intrinsic "
        "relaxation rhythm equal to the cited resting heart rate, " + m("%.2f Hz (%d bpm)" % (D["resting_hz"], D["resting_bpm"])) +
        ". That gives " + m("&kappa; = %.5g s/arb" % D["kappa"]) + ". Nothing else about timing is tuned: every physical "
        "rate is the model rate divided by &kappa;.</p>"
        "<h2>Breathing rate falls out of the &tau;<sub>s</sub> ratio</h2>"
        "<p>Under that one anchor the lung's relaxation rhythm is fixed by the ratio of recovery times, not by a second "
        "fit. The result is " + m("%.2f breaths/min" % D["eupnea_bpm"]) + ", squarely inside the cited eupnea band of "
        "12&ndash;18 breaths/min.</p>"
        "<p>The breath-to-beat ratio " + m("%.3f" % D["ratio_bb"]) + " is therefore structural: it is the &tau;<sub>s</sub> "
        "ratio, not a parameter. The absolute rate carries the cited anchor's grade [L]; the ratio is verified [V].</p>"
        "<h2>Robust across drive</h2>"
        "<p>Sweeping the excitatory drive keeps the breathing rate inside or adjacent to the eupnea band and never "
        "stops the oscillation, so the result is not a fragile operating point.</p>"
        + tbl(["drive","breaths/min","oscillates"],
              [["0.45","17.75","yes"],["0.50","17.34","yes"],["0.55","16.87","yes"],
               ["0.60","16.32","yes"],["0.65","15.67","yes"],["0.70","14.86","yes"]])
    )
    S.append(dict(no=3, title="Eupnea Period from the Shared Oscillator",
        short="Eupnea period", grade_tokens=["[V]","[L]"],
        answer=("With one time anchor &mdash; the heart's intrinsic rhythm set to the cited resting rate %.2f Hz &mdash; "
                "the lung's breathing rate falls out of the recovery-time ratio at %.2f breaths/min, inside the cited "
                "12&ndash;18 band. The breath-to-beat ratio %.3f is structural, not fitted; rate grade [L], ratio [V]." %
                (D["resting_hz"], D["eupnea_bpm"], D["ratio_bb"])),
        abstract=("A single anchor " + m("&kappa; = %.5g s/arb" % D["kappa"]) +
                  (" (heart intrinsic := resting HR %.2f Hz) " % D["resting_hz"]) +
                  "fixes the clock; the &tau;<sub>s</sub> ratio then gives " + m("%.2f breaths/min" % D["eupnea_bpm"]) +
                  " (band 12&ndash;18), ratio " + m("%.3f" % D["ratio_bb"]) + ". [V]/[L]."),
        cards=[C["resting_hr"], C["gamma_lung"]], body=body,
        keys=["%.2f breaths/min" % D["eupnea_bpm"], "breath:beat = %.3f" % D["ratio_bb"]]))

    # ---- 4 apnea / chemoreflex ----
    body = (
        "<h2>Apnea as a delayed-feedback instability</h2>"
        "<p>Periodic breathing (the apnea&ndash;hyperpnea cycle) is modeled as a delayed negative chemoreflex on a "
        "first-order gas plant, " + m("dc/dt = &minus;(c + V<sub>dev</sub>)/T<sub>p</sub>") + " with the ventilatory "
        "deviation " + m("V<sub>dev</sub> = clamp(LG&middot;c(t&minus;&tau;<sub>d</sub>))") + ". The clamp at zero is the "
        "apnea floor: ventilation cannot go negative.</p>"
        "<p>Such a loop is stable at low gain and undergoes a Hopf-type instability when the loop gain LG crosses a "
        "critical value. Normalizing to that critical value, the onset sits at " + m("LG / LG<sub>c</sub> = 1") + ".</p>"
        "<h2>Clean separation across the threshold</h2>"
        "<p>Below threshold the oscillation amplitude settles to zero; above it a sustained limit cycle appears with a "
        "well-defined period (here " + m("&asymp; %.0f s" % D["chemo_T"]) + " at the example delay). The transition is "
        "sharp, with no ambiguous middle band.</p>"
        + tbl(["LG / LG<sub>c</sub>","late amplitude","sustained","apnea fraction"],
              [["0.5","0.00","no","0.00"],["0.7","0.00","no","0.00"],["0.9","&asymp;0","no","0.00"],
               ["1.1","0.94","yes","0.26"]])
        + "<h2>Grade</h2>"
        "<p>The existence of the instability and the apnea clamp are verified [V]; the threshold is reported relative to "
        "its own critical value, so the qualitative law &mdash; loop gain above one drives periodic breathing &mdash; is "
        "the claim, not a tuned absolute number.</p>"
    )
    S.append(dict(no=4, title="Apnea Threshold and Chemoreflex Loop Gain",
        short="Apnea threshold", grade_tokens=["[V]"],
        answer=("Periodic breathing is a delayed-negative-feedback instability of the chemoreflex: ventilation is "
                "floored at zero (the apnea clamp), and the loop is stable until loop gain crosses a critical value. "
                "Normalized to that value the onset is at LG/LG<sub>c</sub> = 1, with a clean stable-to-limit-cycle "
                "separation. Grade [V]."),
        abstract=("A delayed chemoreflex " + m("dc/dt = &minus;(c+V<sub>dev</sub>)/T<sub>p</sub>") + " with apnea clamp "
                  "loses stability via a Hopf bifurcation at " + m("LG/LG<sub>c</sub> = 1") + "; below, amplitude &rarr; 0; "
                  "above, a sustained cycle (&asymp; %.0f s). [V]." % D["chemo_T"]),
        cards=[C["gamma_lung"]], body=body,
        keys=["LG/LG<sub>c</sub> = 1", "apnea fraction 0.26 above threshold"]))

    # ---- 5 RSA ----
    body = (
        "<h2>Respiration modulates the heart</h2>"
        "<p>Respiratory sinus arrhythmia is reproduced by letting the respiratory oscillator frequency-modulate the "
        "cardiac drive, " + m("drive = drive&#8320; + &epsilon;&middot;r(t)") + ". The diagnostic is the heart-rate-"
        "variability spectrum computed from inter-beat intervals.</p>"
        "<p>The lock is defined inside the cited high-frequency HRV window, " + m("0.15&ndash;0.40 Hz") + ", which is the "
        "standard vagal RSA band. This matters: strong coupling pushes a harmonic outside the band, so the peak must be "
        "read within the band to match the physiological definition.</p>"
        "<h2>Lock only when coupled</h2>"
        "<p>Decoupled, the HRV spectrum shows no in-band peak at the respiratory frequency. Coupled, an HF peak appears "
        "essentially at " + m("f<sub>resp</sub> = %.4g Hz" % D["rsa_fresp"]) + " (measured peak " + m("%.4g Hz" % D["rsa_peak"]) +
        "), and it tracks the respiratory frequency as that frequency is scaled.</p>"
        + tbl(["coupling &epsilon;","HRV peak (Hz)","f<sub>resp</sub> (Hz)","in-band lock"],
              [["0.00 (decoupled)","0.303","0.281","no"],["0.02","0.284","0.281","yes"],
               ["0.05","0.278","0.281","yes"],["0.10","0.284","0.281","yes"]])
        + "<h2>Grade</h2>"
        "<p>Coupling creates an HF-HRV peak at the respiratory frequency that is absent when decoupled and that tracks "
        "f<sub>resp</sub>: grade [V]. The band itself is the cited Task-Force window [L].</p>"
    )
    S.append(dict(no=5, title="Respiratory Sinus Arrhythmia",
        short="RSA", grade_tokens=["[V]","[L]"],
        answer=("When the respiratory oscillator frequency-modulates the cardiac drive, a high-frequency heart-rate-"
                "variability peak appears at the respiratory frequency (&asymp; %.2f Hz) inside the cited 0.15&ndash;0.40 Hz "
                "vagal band &mdash; and only when the two oscillators are coupled. The peak tracks the breathing frequency "
                "as it is scaled. Grade [V]." % D["rsa_fresp"]),
        abstract=("Respiratory modulation of cardiac drive yields an HF-HRV peak at " + m("f<sub>resp</sub> &asymp; %.2f Hz" % D["rsa_fresp"]) +
                  " inside the cited " + m("0.15&ndash;0.40 Hz") + " band, present only when coupled and tracking f<sub>resp</sub>. [V]."),
        cards=[C["hf_band"], C["resting_hr"]], body=body,
        keys=["HF-HRV peak at f<sub>resp</sub> &asymp; %.2f Hz" % D["rsa_fresp"], "lock window 0.15&ndash;0.40 Hz"]))

    # ---- 6 Cheyne-Stokes ----
    body = (
        "<h2>The forced number: period &asymp; twice the delay</h2>"
        "<p>Cheyne&ndash;Stokes respiration is the chemoreflex limit cycle in the fast-plant, delay-dominated regime "
        "typical of heart failure. In that regime the cycle period is set by the loop transport delay, and the model "
        "returns a period-versus-delay slope of " + m("%.4g" % D["csr_slope"]) + " &mdash; essentially " +
        m("T<sub>CSR</sub> &asymp; 2 &times; &tau;<sub>circ</sub>") + ".</p>"
        "<p>This factor of two is the forced relation of the page: a delayed negative feedback oscillates with a period "
        "of about twice its loop delay. It is recovered across a range of circulatory delays, not at a single point.</p>"
        + tbl(["circulatory delay (s)","CSR period (s)","period / delay"],
              [["8","17.74","2.22"],["12","25.74","2.15"],["15","31.74","2.12"],["20","41.74","2.09"]])
        + "<h2>Why heart failure lengthens the cycle</h2>"
        "<p>Because the period scales with the transport delay, a slower circulation (a longer lung-to-chemoreceptor "
        "delay, as in low cardiac output) lengthens the Cheyne&ndash;Stokes cycle. The mechanism predicts the clinical "
        "direction directly.</p>"
        "<h2>Grade</h2>"
        "<p>The limit-cycle period scaling as about twice the delay is verified [V] across the delay sweep; the slope "
        "lands at " + m("%.4g" % D["csr_slope"]) + ", within the acceptance band [1.7, 2.4].</p>"
    )
    S.append(dict(no=6, title="Cheyne-Stokes Period and Circulatory Delay",
        short="Cheyne&ndash;Stokes", grade_tokens=["[V]"],
        answer=("Cheyne&ndash;Stokes respiration is the chemoreflex limit cycle in the delay-dominated heart-failure "
                "regime, and its period scales as about twice the circulatory transport delay &mdash; the model returns a "
                "period-versus-delay slope of %.2f, i.e. T<sub>CSR</sub> &asymp; 2&times;&tau;<sub>circ</sub>. A slower "
                "circulation lengthens the cycle. Grade [V]." % D["csr_slope"]),
        abstract=("In the fast-plant regime the chemoreflex cycle obeys " + m("T<sub>CSR</sub> &asymp; 2 &times; &tau;<sub>circ</sub>") +
                  "; the measured period/delay slope is " + m("%.4g" % D["csr_slope"]) + " across delays 8&ndash;20 s "
                  "(band [1.7,2.4]). [V]."),
        cards=[C["gamma_lung"]], body=body,
        keys=["period/delay slope = %.4g" % D["csr_slope"], "T<sub>CSR</sub> &asymp; 2&times;&tau;<sub>circ</sub>"]))

    # ---- 7 baroreflex ----
    body = (
        "<h2>A pressure step is corrected by a rate change</h2>"
        "<p>The baroreflex is modeled at the rate level, because a relaxation oscillator's cycle rate is correctly "
        "insensitive to its drive &mdash; the autonomic loop must set the SA-node operating rate, not its FHN drive. A "
        "blood-pressure disturbance drives a compensating heart-rate command with cited gain and latency.</p>"
        "<p>The static sensitivity is " + m("%g bpm/mmHg" % D["baro_slope"]) + " with the correct sign (a pressure rise "
        "lowers heart rate), matching the cited baroreflex sensitivity. The onset latency is " + m("%.2g s" % D["baro_lat"]) +
        ", at the cited value.</p>"
        "<h2>Linear over the tested range; regulates to setpoint</h2>"
        "<p>The response is linear in the pressure step over &plusmn;20 mmHg, and the closed loop returns pressure to its "
        "setpoint, with heart rate settling at the cited resting value " + m("%d bpm" % D["resting_bpm"]) + ".</p>"
        + tbl(["&Delta;P (mmHg)","&Delta;HR (bpm)","slope","latency (s)","sign"],
              [["&minus;20","+20","&minus;1.0","0.68","correct"],["&minus;10","+10","&minus;1.0","0.68","correct"],
               ["+10","&minus;10","&minus;1.0","0.68","correct"],["+20","&minus;20","&minus;1.0","0.68","correct"]])
        + "<h2>Grade</h2>"
        "<p>Gain and latency are anchored to cited baroreflex values, so this target is grade [L]; the verified content "
        "is the correct sign, linearity, and closed-loop regulation to the cited setpoint.</p>"
    )
    S.append(dict(no=7, title="Baroreflex Correction of Blood Pressure",
        short="Baroreflex", grade_tokens=["[L]"],
        answer=("A blood-pressure step is corrected by an opposite heart-rate change with the cited sensitivity "
                "%g bpm/mmHg and latency %.2g s; the response is linear over &plusmn;20 mmHg and the closed loop "
                "regulates pressure back to its setpoint with heart rate at the cited resting %d bpm. Gain/latency "
                "grade [L]." % (D["baro_slope"], D["baro_lat"], D["resting_bpm"])),
        abstract=("Rate-level baroreflex: " + m("%g bpm/mmHg" % D["baro_slope"]) + " (correct sign), latency " +
                  m("%.2g s" % D["baro_lat"]) + ", linear over &plusmn;20 mmHg, closed-loop regulation to " +
                  m("%d bpm" % D["resting_bpm"]) + ". [L]."),
        cards=[C["resting_hr"]], body=body,
        keys=["baroreflex %g bpm/mmHg" % D["baro_slope"], "setpoint %d bpm" % D["resting_bpm"]]))

    # ---- 8 oncology ----
    rows = [[str(int(p["pack_years"])), "%.2f&times;" % p["RR"], "%.3f" % p["ln_RR"]] for p in D["rr"]]
    body = (
        "<h2>A carcinogen lowers the R19 barrier</h2>"
        "<p>Cell fate is the same R19 bistable switch. A carcinogen is a sustained aberrant bias h<sub>c</sub> that "
        "pushes toward the malignant basin and lowers the barrier the normal basin must climb. The malignant-crossing "
        "rate is Kramers/Arrhenius over that barrier, " + m("rate &prop; exp(&minus;B<sub>eff</sub>/scale)") + ", and "
        "relative risk is " + m("RR(dose) = rate(dose)/rate(0)") + ".</p>"
        "<p>The barrier is derived, not postulated: the three critical points are the real roots of the cubic "
        + m("s&sup3; &minus; &gamma;s &minus; h = 0") + " (three reals inside " + m("|h| &lt; h* = 2(&gamma;/3)^1.5") +
        "), and " + m("B<sub>eff</sub> = U(saddle) &minus; U(basin)") + ". Two exact identities follow and are checked "
        "at import.</p>"
        + tbl(["identity","value","grade"],
              [["B<sub>eff</sub>(h=0) equals substrate barrier &gamma;&sup2;/4", "%.4g" % D["B0_lung"], "[F]"],
               ["barrier-drop slope at the origin equals &radic;&gamma;", "%.4g" % D["rr_slope0"], "[F]"]])
        + "<h2>Dose&ndash;response: monotone, convex, no threshold</h2>"
        "<p>Mapping cumulative tobacco exposure to bias gives a lung-carcinoma relative risk that starts exactly at "
        + m("RR(0) = 1") + ", rises monotonically, and is convex (accelerating) &mdash; reaching " +
        m("%.1f&times;" % D["rr"][-1]["RR"]) + " at 100 pack-years, the Doll &amp; Peto order of magnitude.</p>"
        "<p>There is no threshold: even half a pack-year already gives " + m("RR = %.3f &gt; 1" % D["rr_tiny"]) + ". The "
        "low-dose slope is the forced quantity &radic;&gamma;, so any positive exposure raises risk &mdash; the "
        "linear-no-threshold shape, grade [V].</p>"
        + tbl(["pack-years","relative risk","ln RR"], rows)
        + "<h2>Combination of carcinogens</h2>"
        "<p>Two carcinogens add their bias h. The model then predicts a combined risk that is "
        + m("%.2f&times;" % D["syn_ratio"]) + " the product of the singles &mdash; %s at moderate dose, approaching "
        "multiplicative only in the low-dose limit. This is a falsifiable corollary; empirical agent-pair synergy "
        "varies.</p>" % D["syn_regime"]
        + "<h2>What is open</h2>"
        "<p>The absolute relative-risk magnitude is grade [O]. <b>Obstacle:</b> the switch's effective noise "
        "temperature (scale) and the molecular dose-to-bias conversion are not fixed by substrate geometry and require "
        "an external population-hazard calibration &mdash; exactly as absolute organ size is open while size order is "
        "forced. The forced endpoints (RR(0)=1, no threshold) and the convex shape stand independently of that "
        "calibration.</p>"
    )
    S.append(dict(no=8, title="Carcinogen Dose Response and Relative Risk",
        short="Carcinogen dose&ndash;response", grade_tokens=["[F]","[F]","[V]","[L]","[O]"],
        answer=("A carcinogen is a sustained bias that lowers the R19 switch barrier, so malignant-crossing rate is "
                "Kramers over that barrier and relative risk is rate(dose)/rate(0). The lung-carcinoma curve starts "
                "exactly at RR(0)=1, has no threshold (half a pack-year already gives RR&gt;1), and is convex, reaching "
                "~18&times; at 100 pack-years. Forced endpoints [F]; shape [V]; absolute magnitude [O]."),
        abstract=("Barrier-lowering " + m("B<sub>eff</sub> = U(saddle)&minus;U(basin)") + " from the cubic " +
                  m("s&sup3;&minus;&gamma;s&minus;h=0") + " gives " + m("RR = exp((B&#8320;&minus;B<sub>eff</sub>)/scale)") +
                  "; RR(0)=1 [F], no threshold (slope &radic;&gamma;) [F], convex to ~18&times; at 100 pack-years [V]; "
                  "absolute magnitude [O]."),
        cards=[C["r19_barrier"], C["spinodal"], C["gamma_lung"]], body=body,
        keys=["RR(0) = 1", "RR(100 pack-years) &asymp; %.1f&times;" % D["rr"][-1]["RR"], "no-threshold slope &radic;&gamma;"]))

    # ---- 9 reproducibility ----
    body = (
        "<h2>Grades used on this site</h2>"
        "<p>Every claim carries one grade. [F] forced means it is forced by the substrate with no freedom; [V] verified "
        "means reproduced and checked numerically; [L] calibrated means anchored to a cited literature value; [O] open "
        "means not yet reproducible, and every [O] states its obstacle.</p>"
        + tbl(["grade","meaning","example on this site"],
              [["[F] forced","forced by the R19 substrate","RR(0)=1; no-threshold slope &radic;&gamma;"],
               ["[V] verified","reproduced and checked","shared oscillator; RSA lock; Cheyne&ndash;Stokes 2&times; delay"],
               ["[L] calibrated","anchored to cited values","resting HR; baroreflex gain/latency; HF-HRV band"],
               ["[O] open","not yet reproducible (obstacle stated)","absolute cancer relative-risk magnitude; absolute organ size"]])
        + "<h2>Determinism</h2>"
        "<p>The engine is deterministic: a two-run check produces identical sha256, and the current circulation hash "
        "begins " + m(D["sha"][:16] + "&hellip;") + ". The site cannot be written until the stress battery is green and "
        "research is signed off; that gate produced this site.</p>"
        "<h2>Open items (C3 ledger)</h2>"
        + tbl(["open item","obstacle"],
              [["absolute cancer relative-risk magnitude","noise temperature (scale) and dose-to-bias conversion need external population-hazard calibration"],
               ["absolute organ size","DWELL fixes relative size only; absolute magnitude needs external calibration"]])
        + "<h2>Reproduce</h2>"
        "<p>Run " + m("python repro/run_all.py") + " to emerge the organs, confirm the oscillators, pass the five-target "
        "stress battery, and print the oncology curve and gate status. The per-section reproduction scripts live in the "
        "GitHub repository under the matching slug.</p>"
    )
    S.append(dict(no=9, title="Reproducibility Grades and Open Items",
        short="Reproducibility &amp; grades", grade_tokens=[],
        answer=("Every claim on this site carries one grade: [F] forced by the substrate, [V] reproduced and checked, "
                "[L] anchored to a cited value, [O] open with a stated obstacle. The engine is deterministic (two-run "
                "identical sha256), and writing was gated on a green five-target stress battery. The open items are the "
                "absolute cancer-risk magnitude and absolute organ size."),
        abstract=("Grades: [F] forced, [V] verified, [L] calibrated, [O] open (obstacle stated). Determinism is "
                  "enforced by a two-run identical-sha256 check (current hash " + m(D["sha"][:12] + "&hellip;") +
                  "); the open items carry explicit obstacles."),
        cards=[], body=body,
        keys=["two-run identical sha256", "[O] items state obstacles"]))

    # ---- 10 from DNA: the emergence chain ----
    body = (
        "<h2>The chain: gene &rarr; &gamma; &rarr; R19 switch &rarr; oscillator</h2>"
        "<p>The cardiorespiratory dynamics in this volume descend from DNA, not from a hand-built model. Each organ "
        "begins at a master gene &mdash; NKX2-5 for the heart, NKX2-1 for the lung &mdash; whose promoter stacking "
        "stability &gamma; is read from the 4D-DNA gene-clock.</p>"
        "<p>That single number &gamma; fixes the organ's R19 bistable switch (barrier " + m("B = &gamma;&sup2;/4") +
        ", spinodal " + m("h* = 2(&gamma;/3)^1.5") + "), and the switch's cubic is exactly the fast nonlinearity of the "
        "FitzHugh&ndash;Nagumo relaxation oscillator. So the heartbeat and the breath are two settings of one "
        "DNA-anchored oscillator, separated only by the slow recovery time.</p>"
        "<p>Heart " + m("&gamma;(NKX2-5) = %.4g" % D["g_heart"]) + " and lung " + m("&gamma;(NKX2-1) = %.4g" % D["g_lung"]) +
        " are the measured inputs; everything downstream is derived from them with no further fitting.</p>"
        + tbl(["stage", "heart", "lung", "grade"],
              [["master gene", "NKX2-5", "NKX2-1", "cited (DNA)"],
               ["stacking stability &gamma;", "%.4g" % D["g_heart"], "%.4g" % D["g_lung"], "[V] readout"],
               ["functional spinodal", "%.6g" % D["sp_heart"], "%.6g" % D["sp_lung"], "[F] substrate"],
               ["R19 switch + FHN oscillator", "&tau;<sub>s</sub> = %g" % D["tau_heart"], "&tau;<sub>s</sub> = %g" % D["tau_lung"], "[F]/[V]"],
               ["functional role", "SA-node pacemaker", "preBotzinger rhythm", "[V]"]])
        + "<h2>Why &gamma; is an input, not a fit</h2>"
        "<p>The no-tuning rule is strict: &gamma; is a measured property of the gene, never a knob turned to hit a "
        "target. This is what separates a grounded emergence from a curve fit &mdash; the same &gamma; that orders the "
        "organs also sets the switch barrier and the oscillator, with one value doing all three jobs.</p>"
        "<p>Because the inputs are fixed by DNA, the dynamics are falsifiable: if the measured &gamma; values were "
        "different, the recovery-time ratio, the breathing rate, and the carcinogen low-dose slope would all move "
        "together in the predicted direction.</p>"
        "<h2>Developmental order is a &gamma; readout</h2>"
        "<p>Ordering the two organs by ascending &gamma; gives " + m("%s &rarr; %s" % (D["order_asc"][0], D["order_asc"][1])) +
        ". The emergence order is owned by the DNA gene-clock and read out here; the identity and the order are "
        "established results of the 4D-DNA volume, which this volume builds upon directly.</p>"
        "<h2>What this volume establishes on top of DNA</h2>"
        "<p>From the DNA-anchored oscillator this volume derives the functional layer: the breathing rate, the apnea "
        "threshold, respiratory sinus arrhythmia, the Cheyne&ndash;Stokes period, baroreflex regulation, and a shared "
        "carcinogen dose&ndash;response. Each result is regenerated by a deterministic engine and graded; the grade "
        "ledger and the open items are collected in <a href=\"/" + PAPER_ID + "/09-reproducibility-grades-open-items/\">&sect;9</a>.</p>"
    )
    S.append(dict(no=10, title="From DNA: Master Genes, Stacking Stability, and the R19 Switch",
        short="From DNA: the emergence chain", grade_tokens=["[V]","[V]","[F]"],
        answer=("The cardiorespiratory dynamics descend from DNA: the master genes NKX2-5 (heart) and NKX2-1 (lung) "
                "carry measured stacking stabilities &gamma; read from the 4D-DNA gene-clock, and that one number sets "
                "each organ's R19 bistable switch and its FitzHugh&ndash;Nagumo oscillator. Ascending &gamma; gives the "
                "developmental order. Grades [V] readout and [F] substrate."),
        abstract=("Gene &rarr; &gamma; &rarr; R19 switch &rarr; oscillator: heart " + m("&gamma;(NKX2-5) = %.4g" % D["g_heart"]) +
                  " and lung " + m("&gamma;(NKX2-1) = %.4g" % D["g_lung"]) + " are the measured DNA inputs; the switch "
                  "barrier " + m("&gamma;&sup2;/4") + " and the FHN cubic follow, and ascending &gamma; orders the organs. [V]/[F]."),
        cards=[C["gamma_heart"], C["gamma_lung"], C["fhn"], C["order"]], body=body,
        keys=["&gamma;(NKX2-5) = %.4g" % D["g_heart"], "&gamma;(NKX2-1) = %.4g" % D["g_lung"],
              "master gene NKX2-5 NKX2-1", "4D-DNA gene-clock", "stacking stability", "R19 bistable switch"]))

    # ---- 11 shared-substrate spectrum (disease-extension as mechanism dynamics) ----
    body = (
        "<p>The three primitives established above &mdash; the R19 bistable switch, the FitzHugh&ndash;Nagumo "
        "oscillator, and the delayed chemoreflex loop &mdash; reproduce a spectrum of cardiorespiratory phenomena with "
        "no new mechanism added. These are dynamical signatures of the shared substrate, stated as mechanism, not as "
        "clinical, diagnostic, or management statements.</p>"
        "<h2>Mayer waves: a baroreflex resonance near 0.1 Hz</h2>"
        "<p>Slow arterial-pressure waves near 0.1 Hz emerge as a resonance of the same delayed baroreflex loop that "
        "&sect;7 derives. The frequency is a cited physiological value [L]; the mechanism is the loop, reused without "
        "modification [V].</p>"
        "<h2>Airway-tone switch (asthma regime)</h2>"
        "<p>Reversible airway-tone collapse is the R19 switch run as a reversible bias rather than the one-way "
        "carcinogen bias of &sect;8. The bistable shape and its hysteresis are the reused content [V]; the absolute "
        "provocation magnitude is open [O].</p>"
        "<h2>Pharyngeal patency and loop gain (obstructive-apnea regime)</h2>"
        "<p>Obstructive sleep apnea is read as a two-part dynamical regime: a pharyngeal patency switch on top of the "
        "ventilatory loop-gain instability of &sect;4. The loop-gain endotype is the verified reuse of " +
        m("LG / LG<sub>c</sub> = 1") + " [V]; the absolute collapse pressure is open [O].</p>"
        "<h2>Periodic-breathing spectrum (central-apnea family)</h2>"
        "<p>Altitude, low cardiac output, and opioid-driven periodic breathing form one spectrum: the same chemoreflex "
        "Hopf instability with different loop delays and gains, reusing &sect;4 and &sect;6. The directions and the "
        "delay scaling are verified [V]; the absolute thresholds are open [O].</p>"
        "<h2>Fever: heart-rate and respiratory-rate co-scaling</h2>"
        "<p>Because both organs are one oscillator, a thermal speed-up raises the cardiac and the respiratory rate "
        "together rather than independently. This co-scaling direction is a substrate-distinctive prediction [V]; the "
        "absolute slope is open [O].</p>"
        "<h2>Cough: an all-or-none excitable threshold</h2>"
        "<p>Cough is the FitzHugh&ndash;Nagumo unit in its excitable regime: a sub-threshold stimulus decays, a "
        "supra-threshold stimulus fires a full response. The all-or-none excitation is the reused mechanism [V]; the "
        "absolute stimulus threshold is open [O].</p>"
        + tbl(["phenomenon", "reused primitive", "verified signature", "open magnitude"],
              [["Mayer waves &asymp; 0.1 Hz", "baroreflex loop (&sect;7)", "resonance exists [V]", "frequency cited [L]"],
               ["airway-tone switch", "R19 reversible bias (&sect;8)", "bistable + hysteresis [V]", "provocation [O]"],
               ["obstructive-apnea regime", "loop gain (&sect;4) + patency switch", "loop-gain endotype [V]", "collapse pressure [O]"],
               ["periodic-breathing spectrum", "chemoreflex Hopf (&sect;4, &sect;6)", "directions + delay scaling [V]", "thresholds [O]"],
               ["fever co-scaling", "shared oscillator (&sect;2)", "HR&ndash;RR co-scaling [V]", "slope [O]"],
               ["excitable cough", "FHN excitable regime (&sect;2)", "all-or-none firing [V]", "threshold [O]"]])
        + "<h2>What is open</h2>"
        "<p>Across this spectrum the verified content is the mechanism reuse; every absolute magnitude is grade [O]. "
        "<b>Obstacle:</b> the switch noise scale and the stimulus-to-bias conversion are not fixed by substrate "
        "geometry and need an external calibration &mdash; the same obstacle that keeps absolute organ size and "
        "absolute cancer relative-risk open. The open items are collected in "
        "<a href=\"/" + PAPER_ID + "/09-reproducibility-grades-open-items/\">&sect;9</a>.</p>"
    )
    S.append(dict(no=11, title="Shared-Substrate Cardiorespiratory Spectrum",
        short="Shared-substrate spectrum", grade_tokens=["[V]","[V]","[V]","[O]"],
        answer=("The same three primitives &mdash; the R19 switch, the FitzHugh&ndash;Nagumo oscillator, and the "
                "delayed chemoreflex loop &mdash; reproduce a spectrum of cardiorespiratory phenomena with no new "
                "mechanism: Mayer waves, the airway-tone switch, the obstructive-apnea loop-gain regime, the "
                "periodic-breathing spectrum, fever heart-rate co-scaling, and excitable cough. Signatures [V]; "
                "absolute magnitudes [O]."),
        abstract=("One substrate, six signatures: Mayer waves near 0.1 Hz, an airway-tone bistable switch, the "
                  "obstructive-apnea loop-gain regime, the periodic-breathing spectrum, fever HR&ndash;RR co-scaling, "
                  "and all-or-none cough &mdash; each a reuse of &sect;2/&sect;4/&sect;7 with no new primitive. "
                  "Mechanisms [V]; absolute magnitudes [O]."),
        cards=[C["loop_gain"], C["fhn"], C["r19_barrier"]], body=body,
        keys=["Mayer waves", "obstructive sleep apnea loop gain", "periodic breathing", "airway-tone switch",
              "cough excitable threshold", "fever heart rate respiratory co-scaling"]))

    # ---- 12 methods, determinism, reproducibility apparatus ----
    body = (
        "<h2>One deterministic engine, no tuning</h2>"
        "<p>Every number on this site is regenerated by one deterministic engine: pinned single-thread linear algebra, "
        "a fixed seed, round-before-hash, and sorted-key output. A two-run check yields an identical SHA-256, and the "
        "current circulation hash begins " + m(D["sha"][:16] + "&hellip;") + ".</p>"
        "<p>No constant is chosen to hit a target. The master-gene " + m("&gamma;") + " values are measured DNA inputs, "
        "the time anchor " + m("&kappa; = %.5g s/arb" % D["kappa"]) + " is fixed once by the cited resting rate " +
        m("%.2f Hz" % D["resting_hz"]) + ", and every other rate is a model rate divided by that one anchor.</p>"
        "<h2>The one-command harness and its gates</h2>"
        "<p>A single command, " + m("python repro/run_all.py") + ", emerges the organs from " + m("&gamma;") + ", confirms "
        "the shared oscillator, runs the five-target stress battery and the carcinogen kernel, and then runs eleven "
        "reproducibility gates ending in one line: " + m("OVERALL: PASS (11/11), drift 0") + ".</p>"
        + tbl(["gate", "checks"],
              [["R1 engine determinism", "two engine runs give an identical SHA-256"],
               ["R2 report drift-0", "the whole result blob is byte-identical across recomputation"],
               ["R3 stress battery", "the five T1&ndash;T5 discriminants pass"],
               ["R4 oncology kernel", "RR(0)=1, no threshold, and the barrier matches the substrate"],
               ["R5 shared-substrate spectrum", "every reuse holds with no new primitive"],
               ["R6 file manifest", "every shipped file matches a SHA-256 manifest (fail-closed)"],
               ["R7 forbidden-claim scan", "no drug, dosing, or treatment language on the site (fail-closed)"],
               ["R8 grade legality", "only the four legal grade tokens appear"],
               ["R9 open-item ledger", "every open item on the site states an obstacle"],
               ["R10 concept DOI", "the DOI is embedded site-wide with no placeholder"],
               ["R11 offline", "the engine reproduces with the network disabled"]])
        + "<h2>File-level reproducibility and provenance</h2>"
        "<p>Beyond the engine output, a file-level SHA-256 manifest pins the whole delivered package, so any silent "
        "byte-drift in a shipped file is caught. The concept DOI " + m(DOI) + " is wired into every section page, the "
        "hub, the structured metadata, and the machine-readable index, and a gate fails the build if any surface "
        "drifts.</p>"
        "<p>This reproducibility apparatus was inherited from the analgesic-threshold VP volume and is applied here in "
        "full; the grade vocabulary and the open-item obstacles are defined in "
        "<a href=\"/" + PAPER_ID + "/09-reproducibility-grades-open-items/\">&sect;9</a>.</p>"
        "<h2>Offline and wall-clock-free</h2>"
        "<p>The engine reproduces with the network socket disabled, so the result depends on nothing outside the "
        "package. The build carries no wall-clock: the release date is pinned, so regenerating this site reproduces it "
        "byte-for-byte.</p>"
    )
    S.append(dict(no=12, title="Methods, Determinism, and the Reproducibility Apparatus",
        short="Methods &amp; reproducibility", grade_tokens=["[V]"],
        answer=("Every number is regenerated by one deterministic engine: a two-run identical SHA-256 with drift 0. "
                "A single command emerges the organs, confirms the oscillator, runs the five-target stress battery and "
                "the carcinogen kernel, and then eleven reproducibility gates, while a file-level SHA-256 manifest and "
                "a concept-DOI check pin the whole package. Grade [V]."),
        abstract=("One deterministic engine (two-run identical SHA-256, current hash " + m(D["sha"][:12] + "&hellip;") +
                  "), one command " + m("python repro/run_all.py") + " with eleven gates ending " +
                  m("OVERALL: PASS (11/11), drift 0") + ", a file-level manifest, and a site-wide concept DOI " +
                  m(DOI) + ". Wall-clock-free and offline-reproducible. [V]."),
        cards=[C["kappa"], C["fhn"]], body=body,
        keys=["deterministic engine", "two-run identical SHA-256", "drift 0", "file-level SHA-256 manifest",
              "offline reproducible", "concept DOI " + DOI]))

    # finalize slugs + grade
    for s in S:
        s["slug"] = slugify(s["title"], s["no"])
        s["grade"] = page_grade(s["grade_tokens"])
    return S

# --------------------------------------------------------------------------- URLs / counts
def hub_url():       return DOMAIN + "/" + PAPER_ID + "/"
def sec_url(slug):   return DOMAIN + "/" + PAPER_ID + "/" + slug + "/"
def repro_url(slug): return REPO + "/tree/main/repro/" + PAPER_ID + "/" + slug + "/"

def count_words(body_html):
    txt = html.unescape(re.sub(r"<[^>]+>", " ", body_html))
    return len([w for w in re.split(r"\s+", txt) if w])
def count_inline_math(body_html): return body_html.count('class="m"')
def count_tables(body_html):      return body_html.count("<table")
def plain(s):                     return html.unescape(re.sub("<[^>]+>", "", s))

# --------------------------------------------------------------------------- chapter
def render_chapter(sec, prev, nxt):
    slug, no = sec["slug"], sec["no"]
    ld_article = {
        "@context": "https://schema.org", "@type": "ScholarlyArticle",
        "headline": plain(sec["title"]), "name": plain(sec["title"]),
        "isPartOf": {"@type": "CreativeWorkSeries", "name": SHORT, "sameAs": REPO},
        "position": no, "author": {"@type": "Person", "name": AUTHOR, "sameAs": ORCID},
        "datePublished": BUILD_DATE, "dateModified": BUILD_DATE,
        "isBasedOn": repro_url(slug), "license": LICENSE, "inLanguage": "en",
        "identifier": DOI_URL, "sameAs": [REPO, DOI_URL],
        "knowsAbout": ["jamming lattice", "R19 bistable switch", "relaxation oscillator",
                       "cardiorespiratory control"] + [plain(k) for k in sec["keys"]]}
    ld_crumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": DOMAIN + "/"},
        {"@type": "ListItem", "position": 2, "name": SHORT, "item": hub_url()},
        {"@type": "ListItem", "position": 3, "name": "\u00a7%d %s" % (no, plain(sec["short"]))}]}
    jl = (json.dumps(ld_article, ensure_ascii=False, indent=1) + "\n</script>\n"
          '<script type="application/ld+json">\n' + json.dumps(ld_crumb, ensure_ascii=False, indent=1))
    desc = plain(sec["answer"])[:158]
    head_title = (plain(sec["title"])[:45] + " \u2014 " + SHORT + " \u00a7%d | Jamming Physics" % no)
    grade_span = ('<span class="grade %s">%s %s</span>' % (
        GRADE_CLASS[sec["grade"]], sec["grade"], GRADE_WORD[sec["grade"]].split(" ")[0])
        if sec["grade"] else "")
    doi_bit = ('<a class="doi" href="' + DOI_URL + '" rel="noopener">DOI ' + DOI + '</a>'
               if not DOI_PENDING else '<span class="doi-pending">DOI: pending archival (Zenodo)</span>')
    cards_html = "".join(sec["cards"])
    prev_a = ('<a rel="prev" href="/%s/%s/">\u2190 \u00a7%d</a>' % (PAPER_ID, prev["slug"], prev["no"])
              if prev else '<span class="pn-end">start</span>')
    next_a = ('<a rel="next" href="/%s/%s/">\u00a7%d \u2192</a>' % (PAPER_ID, nxt["slug"], nxt["no"])
              if nxt else '<span class="pn-end">end</span>')
    return (
'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
'<meta name="viewport" content="width=device-width, initial-scale=1">\n'
'<title>' + html.escape(head_title) + '</title>\n'
'<meta name="description" content="' + html.escape(desc) + '">\n'
'<link rel="canonical" href="' + sec_url(slug) + '">\n'
+ seo_meta(plain(sec["title"]), desc, sec_url(slug), "article", sec["keys"]) +
'<link rel="stylesheet" href="/assets/css/site.css">\n'
'<script type="application/ld+json">\n' + jl + '\n</script>\n'
'</head>\n<body>\n'
'<header><nav class="crumb"><a href="/">Home</a> \u203a <a href="/' + PAPER_ID + '/">' + SHORT +
'</a> \u203a \u00a7' + str(no) + '</nav></header>\n<main>\n'
'<h1>' + sec["title"] + '</h1>\n'
'<p class="answer">' + sec["answer"] + '</p>\n'
'<p class="abstract">' + sec["abstract"] + '</p>\n'
'<aside class="claim-strip">' + grade_span +
'<span class="gate">LOCK \u2192 Derive \u2192 Gate</span>'
'<a href="' + repro_url(slug) + '" rel="noopener">Reproduction code (GitHub)</a>' + doi_bit + '</aside>\n'
+ (cards_html + "\n" if cards_html else "") + sec["body"] +
'\n<nav class="pn">' + prev_a + '<a href="/' + PAPER_ID + '/">Contents</a>' + next_a + '</nav>\n'
'</main>\n<footer>' + AUTHOR + ' \u00b7 <a href="' + ORCID + '" rel="noopener">ORCID</a> \u00b7 '
'<a href="' + REPO + '" rel="noopener">Reproduction repo</a> \u00b7 '
'<a href="' + LICENSE + '" rel="noopener">CC BY 4.0</a> \u00b7 '
'<a href="' + DOI_URL + '" rel="noopener">DOI ' + DOI + '</a></footer>\n'
'</body>\n</html>\n')

# --------------------------------------------------------------------------- hub
def render_hub(S, D):
    ld = {"@context": "https://schema.org", "@type": "CreativeWorkSeries",
          "name": TITLE, "alternateName": SHORT, "sameAs": [REPO, DOI_URL],
          "identifier": DOI_URL,
          "author": {"@type": "Person", "name": AUTHOR, "sameAs": ORCID},
          "license": LICENSE, "inLanguage": "en",
          "hasPart": [{"@type": "ScholarlyArticle", "name": plain(s["title"]),
                       "position": s["no"], "url": sec_url(s["slug"])} for s in S]}
    ld_crumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": DOMAIN + "/"},
        {"@type": "ListItem", "position": 2, "name": SHORT, "item": hub_url()}]}
    toc = ""
    for s in S:
        g = ('<span class="grade %s">%s</span>' % (GRADE_CLASS[s["grade"]], s["grade"])) if s["grade"] else ""
        toc += ('<li><a href="/' + PAPER_ID + '/' + s["slug"] + '/">\u00a7' + str(s["no"]) + " " +
                s["short"] + "</a> " + g + '<br><span class="one">' +
                plain(s["answer"])[:120] + "\u2026</span></li>\n")
    jl = (json.dumps(ld, ensure_ascii=False, indent=1) + "\n</script>\n"
          '<script type="application/ld+json">\n' + json.dumps(ld_crumb, ensure_ascii=False, indent=1))
    return (
'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
'<meta name="viewport" content="width=device-width, initial-scale=1">\n'
'<title>' + html.escape((SHORT + " \u2014 heart & lung as one oscillator | Jamming Physics")[:90]) + '</title>\n'
'<meta name="description" content="' + html.escape((
    "Heart (NKX2-5) and lung (NKX2-1) emerge as one FitzHugh-Nagumo relaxation oscillator; eupnea, apnea threshold, "
    "RSA, Cheyne-Stokes, baroreflex, and an R19 carcinogen dose-response kernel.")[:158]) + '">\n'
'<link rel="canonical" href="' + hub_url() + '">\n'
+ seo_meta(TITLE, (
    "Heart (NKX2-5) and lung (NKX2-1) emerge from measured master-gene stacking stabilities as one "
    "FitzHugh-Nagumo relaxation oscillator; eupnea, apnea threshold, RSA, Cheyne-Stokes, baroreflex, "
    "and an R19 carcinogen dose-response, every result graded and deterministically reproduced."),
    hub_url(), "website",
    ["heart lung one oscillator", "cardiorespiratory emergence", "DNA-grounded physiology"]) +
'<meta name="citation_title" content="' + html.escape(TITLE) + '">\n'
'<meta name="citation_author" content="' + html.escape(AUTHOR) + '">\n'
'<meta name="citation_publication_date" content="' + BUILD_DATE.replace("-", "/") + '">\n'
'<meta name="citation_doi" content="' + DOI + '">\n'
'<meta name="citation_pdf_url" content="' + DOI_URL + '">\n'
'<meta name="citation_technical_report_institution" content="jamming-physics.org (independent research)">\n'
'<link rel="stylesheet" href="/assets/css/site.css">\n'
'<script type="application/ld+json">\n' + jl + '\n</script>\n'
'</head>\n<body>\n<header><nav class="crumb"><a href="/">Home</a> \u203a ' + SHORT + '</nav></header>\n<main>\n'
'<h1>' + TITLE + '</h1>\n'
'<p class="answer">This volume derives from the jamming branch of VP Theory \u2192 <a href="/physics/">/physics/</a>. '
'Heart and lung are emerged from their measured master-gene stacking stabilities and shown to be the same relaxation '
'oscillator; their reflex loops and coupling, and a shared R19 oncology kernel, follow from that one substrate with '
'deterministic, graded results.</p>\n'
'<p class="abstract">Resting heart rate ' + ("%.2f Hz" % D["resting_hz"]) + ' is the single time anchor. Breathing '
'rate ' + ("%.2f/min" % D["eupnea_bpm"]) + ', the apnea threshold (loop gain &asymp; 1), RSA (HF-HRV lock), the '
'Cheyne\u2013Stokes period (&asymp; 2\u00d7 delay), and baroreflex regulation are reproduced; cancer relative risk '
'rises from RR(0)=1 with no threshold.</p>\n'
'<h2>Sections</h2>\n<ol class="toc">\n' + toc + '</ol>\n'
'<h2>Grade ledger</h2>\n'
'<p>Every claim is graded: [F] forced by the substrate, [V] reproduced and checked, [L] anchored to a cited value, '
'[O] open with a stated obstacle. The two open items are the absolute cancer relative-risk magnitude and absolute '
'organ size; both are detailed in <a href="/' + PAPER_ID + '/09-reproducibility-grades-open-items/">\u00a79</a>.</p>\n'
'<h2>Related volumes</h2>\n'
'<p>Organ identity and developmental order are cited from the <a href="/dna/">4D-DNA Blueprint</a>; the R19 switch '
'and jamming-lattice substrate are from <a href="/physics/">VP Theory</a>; the felt/interoceptive arm is in '
'<a href="/mind/">Felt Cognition</a>, which cites this volume for cardiac mechanism. The full DNA emergence chain '
'for this volume &mdash; gene &rarr; &gamma; &rarr; R19 switch &rarr; oscillator &mdash; is set out in '
'<a href="/' + PAPER_ID + '/10-dna-master-genes-stacking-stability/">\u00a710</a>.</p>\n'
'</main>\n<footer>' + AUTHOR + ' \u00b7 <a href="' + ORCID + '" rel="noopener">ORCID</a> \u00b7 '
'<a href="' + REPO + '" rel="noopener">Reproduction repo</a> \u00b7 <a href="' + LICENSE +
'" rel="noopener">CC BY 4.0</a></footer>\n</body>\n</html>\n')

# --------------------------------------------------------------------------- top index
def render_index(S, D):
    ld = {"@context": "https://schema.org", "@type": "WebSite", "name": "Jamming Physics",
          "url": DOMAIN + "/", "author": {"@type": "Person", "name": AUTHOR, "sameAs": ORCID}}
    return (
'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
'<meta name="viewport" content="width=device-width, initial-scale=1">\n'
'<title>' + html.escape("Jamming Physics \u2014 Cardiorespiratory volume")[:90] + '</title>\n'
'<meta name="description" content="' + html.escape((
    "Jamming Physics: the vacuum and biology from one jammed-lattice substrate. Cardiorespiratory volume \u2014 heart "
    "and lung as one relaxation oscillator under reflex control.")[:158]) + '">\n'
'<link rel="canonical" href="' + DOMAIN + '/">\n'
+ seo_meta("Jamming Physics \u2014 Cardiorespiratory volume", (
    "The vacuum and biology from one jammed-lattice substrate. Cardiorespiratory volume: heart and lung "
    "emerge from DNA as one relaxation oscillator under reflex control, with deterministic graded results."),
    DOMAIN + "/", "website", ["jamming lattice substrate", "physics and biology one premise"]) +
'<link rel="stylesheet" href="/assets/css/site.css">\n'
'<script type="application/ld+json">\n' + json.dumps(ld, ensure_ascii=False, indent=1) + '\n</script>\n'
'</head>\n<body>\n<header><nav class="crumb">Jamming Physics</nav></header>\n<main>\n'
'<h1>Jamming Physics</h1>\n'
'<p class="answer">Jamming Physics derives physics and biology from one premise: the vacuum is a jammed granular '
'medium with a single bistable switch (R19). This page is the entry point for the Cardiorespiratory volume, in which '
'the heart and lung emerge as the same relaxation oscillator and their reflex control and cancer dose-response follow '
'from that substrate.</p>\n'
'<h2 class="card-h"><a href="/' + PAPER_ID + '/">' + TITLE + '</a></h2>\n'
'<p class="abstract">Heart (NKX2-5) and lung (NKX2-1) share one FitzHugh\u2013Nagumo oscillator; resting HR '
+ ("%.2f Hz" % D["resting_hz"]) + ' anchors time, and eupnea, apnea threshold, RSA, Cheyne\u2013Stokes, baroreflex, '
'and an R19 carcinogen dose-response kernel are reproduced deterministically. Headline result: '
'<span class="m">RR(0)=1</span> with no threshold and a convex dose-response. '
'<a href="/' + PAPER_ID + '/">Open the volume \u2192</a></p>\n'
'<h2>The program</h2>\n'
'<p>This volume is a sibling of the main Jamming Physics papers \u2014 <a href="/physics/">VP Theory</a>, '
'<a href="/cosmology/">Vacuum-Inflow Cosmology</a>, <a href="/fluid-dynamics/">The Configured Continuum</a>, '
'<a href="/geodynamics/">Jamming Geodynamics</a>, <a href="/dna/">4D-DNA Blueprint</a>, '
'<a href="/geochronology/">Cross-Chronometer Limit</a>, <a href="/chemistry/">VP Chemistry &amp; EM</a>, '
'<a href="/neuro/">Neural Emergence Chain</a>, and <a href="/mind/">Felt Cognition</a> \u2014 all derived from the '
'same jamming-lattice substrate by the same author.</p>\n'
'</main>\n<footer>' + AUTHOR + ' \u00b7 <a href="' + ORCID + '" rel="noopener">ORCID</a> \u00b7 '
'<a href="' + REPO + '" rel="noopener">Reproduction repo</a> \u00b7 <a href="' + LICENSE +
'" rel="noopener">CC BY 4.0</a></footer>\n</body>\n</html>\n')

# --------------------------------------------------------------------------- meta / sitemap / robots / llms / css
def render_meta(S, D):
    chapters = []
    for s in S:
        b = s["body"]
        chapters.append({"no": s["no"], "slug": s["slug"], "title": plain(s["title"]),
                         "one_liner": plain(s["answer"])[:120],
                         "grade": (GRADE_WORD[s["grade"]].split(" ")[0] if s["grade"] else None),
                         "words": count_words(b), "eq_inline": count_inline_math(b),
                         "eq_display": 0, "tables": count_tables(b)})
    totals = {"words": sum(c["words"] for c in chapters), "eq": sum(c["eq_inline"] for c in chapters),
              "figures": 0, "tables": sum(c["tables"] for c in chapters)}
    return {"paper_id": PAPER_ID, "code": CODE, "title": TITLE, "short": SHORT,
            "doi": DOI, "doi_url": DOI_URL, "doi_status": "archived (Zenodo concept DOI)",
            "hub_url": "/" + PAPER_ID + "/", "branch": "jamming", "build_date": BUILD_DATE,
            "result_sha256": D["sha"],
            "abstract": ("Heart and lung emerge from measured master-gene stacking stabilities as one relaxation "
                         "oscillator; from a single resting-heart-rate time anchor the model derives eupnea, the apnea "
                         "threshold, respiratory sinus arrhythmia, the Cheyne-Stokes period, baroreflex regulation, and "
                         "a shared R19 carcinogen dose-response kernel with forced no-threshold relative risk."),
            "headline_results": ["heart, lung = one FitzHugh-Nagumo oscillator",
                                 "eupnea %.2f/min from tau_s ratio" % D["eupnea_bpm"],
                                 "Cheyne-Stokes period ~ 2x circulatory delay",
                                 "carcinogen RR(0)=1, no threshold, convex"],
            "chapters": chapters, "totals": totals,
            "grades_legend": {"[F]": "forced", "[V]": "verified", "[L]": "calibrated", "[O]": "open"}}

def render_sitemap(S):
    urls = [DOMAIN + "/", hub_url()] + [sec_url(s["slug"]) for s in S]
    items = "".join("<url><loc>%s</loc><lastmod>%s</lastmod></url>\n" % (u, BUILD_DATE) for u in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + items + '</urlset>\n')

def render_robots():
    bots = ["Googlebot", "Bingbot", "OAI-SearchBot", "GPTBot", "PerplexityBot", "ClaudeBot", "Google-Extended"]
    blocks = "".join("User-agent: %s\nAllow: /\n\n" % b for b in bots)
    return (blocks + "User-agent: *\nAllow: /\n\nSitemap: " + DOMAIN + "/sitemap.xml\n")

def render_llms(S, D):
    by_no = {s["no"]: s for s in S}
    def line(no):
        s = by_no[no]
        return "- [\u00a7%d %s](%s)" % (no, plain(s["short"]), sec_url(s["slug"]))
    lines = []
    lines.append("# Jamming Physics \u2014 Cardiorespiratory volume\n")
    lines.append("> Heart (NKX2-5) and lung (NKX2-1) are emerged from their measured master-gene stacking "
                 "stabilities and shown to be the SAME FitzHugh-Nagumo relaxation oscillator, differing only in the "
                 "slow recovery time. From one cited time anchor (resting heart rate %.2f Hz) the model derives "
                 "breathing rate, the apnea (periodic-breathing) threshold, respiratory sinus arrhythmia, the "
                 "Cheyne-Stokes period, and baroreflex regulation; a shared R19 bistable-switch kernel gives a "
                 "carcinogen dose-response with RR(0)=1, no threshold, and a convex shape. Every claim is graded "
                 "[F]/[V]/[L]/[O] and every number is regenerated by a deterministic engine.\n" % D["resting_hz"])
    lines.append("## Core")
    lines.append("- [Volume hub](%s): heart & lung as one DNA-anchored oscillator, grade ledger, related volumes." % hub_url())
    lines.append(line(1) + ": overview of the emergence and the functional results.")
    lines.append(line(10) + ": the DNA emergence chain (gene -> gamma -> R19 switch -> oscillator).")
    lines.append(line(2) + ": the shared FitzHugh-Nagumo relaxation oscillator.")
    lines.append("\n## Research (derived functional results)")
    for no in (3, 4, 5, 6, 7, 8):
        lines.append(line(no))
    lines.append("\n## Extension")
    lines.append(line(11) + ": Mayer waves, airway-tone switch, obstructive-apnea regime, periodic breathing, fever co-scaling, cough.")
    lines.append("\n## Methods & policies")
    lines.append(line(12) + ": deterministic engine, one-command harness, file-level manifest, offline reproducibility.")
    lines.append(line(9) + ": grade meanings, determinism, open-item obstacles.")
    lines.append("- Reproduction code: %s" % REPO)
    lines.append("- Concept DOI: %s (%s)" % (DOI, DOI_URL))
    lines.append("- License: CC BY 4.0 (%s)\n" % LICENSE)
    return "\n".join(lines)

def render_css():
    return """:root{
  --bg:#faf8f3; --ink:#1c1a17; --muted:#5c574e; --line:#e3ddd1; --card:#fffefb;
  --accent:#7a2e1d; --accent2:#0b6b5f;
  --f:#0b6b5f; --v:#1f6feb; --h:#9a6a00; --l:#5b3fa0; --o:#9a3b3b;
}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--ink);line-height:1.6;
  font-family:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,"Times New Roman",serif;
  font-size:18px}
header,main,footer{max-width:46rem;margin:0 auto;padding:0 1.15rem}
header{padding-top:1.1rem}
.crumb{font-size:.82rem;color:var(--muted);letter-spacing:.01em;
  font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.crumb a{color:var(--muted);text-decoration:none;border-bottom:1px solid var(--line)}
.crumb a:hover{color:var(--accent)}
main{padding-top:.4rem;padding-bottom:2.4rem}
h1{font-size:1.92rem;line-height:1.18;margin:.7rem 0 .55rem;letter-spacing:-.01em}
h2{font-size:1.3rem;margin:2.1rem 0 .5rem;letter-spacing:-.005em;
  border-bottom:1px solid var(--line);padding-bottom:.22rem}
h3{font-size:1.08rem;margin:1.3rem 0 .35rem}
p{margin:.55rem 0}
a{color:var(--accent)}
a:hover{color:var(--accent2)}
.answer{font-size:1.12rem;line-height:1.55;background:var(--card);border:1px solid var(--line);
  border-left:3px solid var(--accent);border-radius:.5rem;padding:.85rem 1rem;margin:.7rem 0 .9rem}
.abstract{color:var(--muted);font-style:italic}
.m{font-family:"SFMono-Regular",ui-monospace,"JetBrains Mono",Menlo,Consolas,monospace;
  font-style:normal;font-size:.9em;background:#f1ece1;padding:.06em .34em;border-radius:.28em;
  white-space:nowrap}
.claim-strip{display:flex;flex-wrap:wrap;gap:.45rem;align-items:center;margin:.7rem 0 1rem;
  font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;font-size:.78rem}
.claim-strip a,.gate,.doi-pending,.doi{padding:.2rem .55rem;border-radius:999px;border:1px solid var(--line);
  background:var(--card);text-decoration:none;color:var(--muted)}
.claim-strip a:hover{border-color:var(--accent);color:var(--accent)}
.grade{padding:.2rem .6rem;border-radius:999px;color:#fff;font-weight:600;
  font-family:ui-sans-serif,system-ui,sans-serif;font-size:.78rem}
.g-forced{background:var(--f)} .g-verified{background:var(--v)} .g-hypothesis{background:var(--h)}
.g-calibrated{background:var(--l)} .g-open{background:var(--o)}
.vp-card{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--accent2);
  border-radius:.5rem;padding:.6rem .8rem;margin:.55rem 0;font-size:.92rem;
  font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;line-height:1.5}
.vp-card b{color:var(--ink)} .vp-card a{font-size:.85em}
table{border-collapse:collapse;width:100%;margin:.9rem 0;font-size:.92rem;
  font-family:ui-sans-serif,system-ui,-apple-system,sans-serif}
th,td{border:1px solid var(--line);padding:.4rem .55rem;text-align:left;vertical-align:top}
thead th{background:#f1ece1;font-weight:600}
tbody tr:nth-child(even){background:#fcfaf5}
ol.toc{list-style:none;padding:0;margin:1rem 0}
ol.toc li{padding:.6rem 0;border-bottom:1px solid var(--line)}
ol.toc a{text-decoration:none;font-weight:600;font-size:1.05rem}
.one{color:var(--muted);font-size:.86rem;font-style:italic}
.card-h{border:none;margin-top:1.4rem}
.card-h a{text-decoration:none}
.pn{display:flex;justify-content:space-between;gap:.6rem;margin:2.2rem 0 .5rem;
  font-family:ui-sans-serif,system-ui,sans-serif;font-size:.86rem}
.pn a{text-decoration:none;padding:.35rem .7rem;border:1px solid var(--line);border-radius:.4rem;
  background:var(--card)}
.pn a:hover{border-color:var(--accent)} .pn-end{color:var(--muted);padding:.35rem .7rem}
footer{border-top:1px solid var(--line);margin-top:2rem;padding-top:1rem;padding-bottom:2.5rem;
  color:var(--muted);font-size:.8rem;
  font-family:ui-sans-serif,system-ui,-apple-system,sans-serif}
footer a{color:var(--muted)}
@media (max-width:600px){body{font-size:17px}h1{font-size:1.62rem}.claim-strip{font-size:.74rem}}
"""

# --------------------------------------------------------------------------- writer
def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def main():
    locked, why = gates.writing_locked()
    if locked:
        print("REFUSED: writing is locked.\nReason:", why)
        print("Sign off research first: gates.write_research_complete(), then  echo writing > PHASE")
        return 1

    D = gather()
    S = build_sections(D)

    # per-section pages
    for i, s in enumerate(S):
        prev = S[i - 1] if i > 0 else None
        nxt  = S[i + 1] if i < len(S) - 1 else None
        write(os.path.join(_DOCS, PAPER_ID, s["slug"], "index.html"), render_chapter(s, prev, nxt))

    # hub, meta, top index, sitemap, robots, llms, css
    write(os.path.join(_DOCS, PAPER_ID, "index.html"), render_hub(S, D))
    write(os.path.join(_DOCS, PAPER_ID, "_meta.json"),
          json.dumps(render_meta(S, D), ensure_ascii=False, indent=2))
    write(os.path.join(_DOCS, "index.html"), render_index(S, D))
    write(os.path.join(_DOCS, "sitemap.xml"), render_sitemap(S))
    write(os.path.join(_DOCS, "robots.txt"), render_robots())
    write(os.path.join(_DOCS, "llms.txt"), render_llms(S, D))
    write(os.path.join(_DOCS, "assets", "css", "site.css"), render_css())

    # manifest CSV (derived index of the canonical HTML)
    rows = ["slug,title,section_no,status,grade,words,eq_display"]
    for s in S:
        rows.append("%s,%s,%d,published,%s,%d,0" % (
            s["slug"], '"' + plain(s["title"]).replace('"', "'") + '"', s["no"],
            (s["grade"] or "-"), count_words(s["body"])))
    write(_MANI, "\n".join(rows) + "\n")

    # report
    n_pages = len(S) + 2  # sections + hub + index
    llms_kb = len(render_llms(S, D).encode("utf-8")) / 1024.0
    print("BUILT canonical site under docs/  (VP-SPEC v1.8)")
    print("  sections        : %d  (+ hub + top index = %d HTML pages)" % (len(S), n_pages))
    print("  result sha256   : %s" % D["sha"][:16])
    print("  llms.txt size   : %.2f KB  (<5KB: %s)" % (llms_kb, llms_kb < 5))
    print("  robots bots     : Googlebot Bingbot OAI-SearchBot GPTBot PerplexityBot ClaudeBot Google-Extended")
    print("  DOI             : %s (concept, Zenodo)" % DOI)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
