#!/usr/bin/env python3
"""tools/make_manifest.py — build registry/vp.manifest.json + append registry/lineage.jsonl.

Source of volume data: tools/master.json (generated by the homepage builder).
Adds: framework kernel/governance/contract/tiers, primitive index (measured),
per-volume inherits/adds, per-volume content hash, and a lineage hash-chain entry.
Run from the repo root (the dir containing docs/, registry/, tools/).
"""
import json, hashlib, glob, os, re, datetime, sys

ROOT = os.getcwd()
DOCS = "docs"
MASTER = os.path.join("tools", "master.json")
MANIFEST = os.path.join("registry", "vp.manifest.json")
LINEAGE = os.path.join("registry", "lineage.jsonl")

ORDER = ['physics','fluid-dynamics','cosmology','chemistry','geodynamics','geochronology',
 'wave-computer','dna','inheritance','neuro','mind','sensory_organ','eye','ear','nose',
 'cardioresp','circulatory','digestive','musculoskeletal','immune_hematologic','integumentary',
 'reproductive_endocrine','homeostasis_thermometabolic','homeostasis_hemodynamic',
 'homeostasis_ionic','circadian','aging_senescence','analgesic_threshold','disease_wp','disease_kit']

# inherits -> adds (from the declared inheritance contract; see AGENTS.md §3.3)
REL = {
 'physics':([],["jammed-substrate","c2=B/rho","R19-normal-form","constants:mp/me=6pi^5"]),
 'fluid-dynamics':(["physics"],["continuum-flow-on-jammed-medium"]),
 'cosmology':(["physics"],["vacuum-inflow","a0=cH0/2pi"]),
 'chemistry':(["physics"],["EM-on-same-substrate","phi_RCP=0.7405","bonding"]),
 'geodynamics':(["physics","fluid-dynamics"],["jamming-unjamming-yield","plate-breakup"]),
 'geochronology':(["physics","geodynamics"],["incorporation-dating-limit"]),
 'wave-computer':(["physics","neuro"],["clock-free-phase-computation"]),
 'dna':(["physics"],["gamma-ruler","two-layer-reading:gamma-LEVEL+A4-SHAPE","R19-in-biology","node-atlas(single-source-of-truth)"]),
 'inheritance':(["dna"],["writable-A4-vs-unwritable-gamma","environmental-inheritance","RNA-layer","gene-therapy-path"]),
 'neuro':(["physics","chemistry","dna"],["neuron=R19+slow-recovery","brain-rhythms","working-memory=theta/gamma~7pm2","memory","motor"]),
 'mind':(["neuro","dna"],["engram=bistable-attractor","felt-cognition","mood=persistent-switch","stream-of-thought"]),
 'sensory_organ':(["dna","neuro"],["organ-dynamics:Hopf-cube-root","instrument-physics"]),
 'eye':(["physics:wave","dna","neuro"],["high-low-down-conversion-ladder","single-photon-R19","Snell:n=sqrt(B/rho)","cube-root"]),
 'ear':(["physics:wave+cubic","dna"],["place-map","cube-root-cochlear-amplifier","otoferlin-readout"]),
 'nose':(["dna"],["combinatorial-code","transduction-switch","anosmia"]),   # selective: no wave module
 'cardioresp':(["dna","circadian","aging_senescence","homeostasis_hemodynamic"],["heart+lung=one-FitzHugh-Nagumo-oscillator"]),
 'circulatory':(["dna","circadian","aging_senescence"],["MAP=CO*SVR","clearance"]),
 'digestive':(["dna","circadian","aging_senescence"],["one-clock:gastric->duodenum"]),
 'musculoskeletal':(["dna","circadian","aging_senescence"],["structure+mechanical-load-from-gamma"]),
 'immune_hematologic':(["dna","circadian","aging_senescence"],["population-thresholds-on-R19"]),
 'integumentary':(["dna","circadian","aging_senescence"],["barrier+external-stimulus","UV->melanoma-key"]),
 'reproductive_endocrine':(["dna","circadian","aging_senescence"],["four-organs-in-measured-gamma-order"]),
 'homeostasis_thermometabolic':(["digestive","aging_senescence","circadian"],["OU-setpoint-three-levers","endo-vs-ecto-sensitivity"]),
 'homeostasis_hemodynamic':(["cardioresp","circulatory","circadian"],["MAP=CVP+CO*SVR-defended"]),
 'homeostasis_ionic':(["musculoskeletal","circadian"],["mineral/acid-base/electrolyte-setpoints"]),
 'circadian':(["dna"],["time-layer:measured-BMAL1-gamma=1.33348"]),
 'aging_senescence':(["dna"],["setpoint-drift-over-time","aging-genes-not-special(|z|<1)"]),
 'analgesic_threshold':(["neuro"],["three-lever-L1/L2/L3-therapeutic-logic"]),
 'disease_wp':(["dna"],["per-disease-gene-key-mechanism-cases"]),
 'disease_kit':(["disease_wp"],["reproducible-corrective-direction[F]","magnitude[O]"]),
}
SELECTIVE = {'nose':"inherits no wave module (smell has no wave)"}

PRIM_PATTERNS = {
 "R19":       r'R19|bistable',
 "gamma":     r'SantaLucia|stacking|spinodal|ΔG37',
 "emergence": r'emerge|emergence|emerges',
 "jammed_c2": r'jammed|random close pack|B/ρ|0\.7405',
 "kramers":   r'Kramers|Arrhenius|escape rate',
 "fhn":       r'FitzHugh|Nagumo|FHN|relaxation oscillat',
 "cube_root": r'cube-?root|\(F/β\)|\^\(1/3\)',
}
PRIM_FORM = {
 "R19":"ds/dt = g*s - s^3 + h","gamma":"gamma = -mean NN stacking dG",
 "emergence":"STATE=presence; spinodal(gamma)=order; dwell~gamma^1.5=size",
 "jammed_c2":"c^2 = B/rho (random close packing)","kramers":"escape over g^2/4",
 "fhn":"relaxation oscillator","cube_root":"R = (F/beta)^(1/3)",
}

def sha256_bytes(b): return hashlib.sha256(b).hexdigest()

def dir_content_hash(base):
    """Deterministic tree hash over all files under base/ (sorted relpath). '' if absent."""
    if not os.path.isdir(base):
        return None
    parts = []
    for f in sorted(glob.glob(os.path.join(base, "**", "*"), recursive=True)):
        if os.path.isfile(f):
            rel = os.path.relpath(f, base)
            parts.append(rel + ":" + sha256_bytes(open(f, "rb").read()))
    return sha256_bytes("\n".join(parts).encode())

def prim_membership():
    blobs = {v: "" for v in ORDER}
    for v in ORDER:
        s = []
        for f in glob.glob(os.path.join(DOCS, v, "**", "*.html"), recursive=True):
            s.append(open(f, encoding="utf-8", errors="replace").read())
        blobs[v] = "".join(s)
    out = {}
    for name, pat in PRIM_PATTERNS.items():
        vols = [v for v in ORDER if re.search(pat, blobs[v])]
        out[name] = {"form": PRIM_FORM[name], "pattern": pat,
                     "count": len(vols), "volumes": vols}
    return out

def main():
    M = {r["paper_id"]: r for r in json.load(open(MASTER))}
    prims = prim_membership()

    volumes = []
    for vid in ORDER:
        r = M[vid]
        inh, add = REL.get(vid, ([], []))
        row = {
            "id": vid, "tier": r["tier"], "short": r["short"],
            "doi": r["doi"], "hub": r["hub"], "headline": r["hl"],
            "inherits": inh, "adds": add,
            "primitives": [k for k, d in prims.items() if vid in d["volumes"]],
            "grades": r["grades"], "pages": r["pages"],
            "content_sha256": dir_content_hash(os.path.join(DOCS, vid)),
            "repro_sha256": dir_content_hash(os.path.join("repro", vid)),
        }
        if vid in SELECTIVE: row["selective"] = SELECTIVE[vid]
        volumes.append(row)

    manifest = {
        "schema": "vp.manifest/1.0",
        "framework": {
            "name": "VP — Vacuum / Jamming Physics",
            "site": "https://jamming-physics.org/",
            "author": {"name": "Young Jae Lee", "orcid": "0009-0002-7535-8245"},
            "license": "CC-BY-4.0",
            "kernel": {
                "substrate": "c^2 = B/rho (vacuum = jammed elastic solid, phi~0.7405)",
                "switch": "ds/dt = g*s - s^3 + h  (R19 bistable)",
                "stiffness": "gamma = -mean NN stacking dG  (measured, never fitted)",
                "emergence": "STATE=presence; spinodal(gamma)=order; dwell~gamma^1.5=size",
            },
            "governance": ["no-tuning", "LOCK->Derive->Gate", "honest-grading[F/V/L/O]",
                           "magnitude-firewall", "seed=19", "2x-SHA256"],
            "contract": ["dna-atlas=single-source-of-truth", "add-only",
                         "selective-inheritance", "provenance-not-targets", "sharp-seams"],
            "tiers": {"1": "foundation", "2": "bridge", "3": "inheritance", "4": "neural",
                      "5": "sensory", "6": "organ", "7": "homeostasis-time", "8": "disease"},
            "guide": "/AGENTS.md",
        },
        "primitives": prims,
        "volumes": volumes,
        "lineage": {},  # filled below
    }

    # --- lineage hash-chain ---
    prev = None
    if os.path.exists(LINEAGE):
        lines = [l for l in open(LINEAGE, encoding="utf-8").read().splitlines() if l.strip()]
        if lines:
            prev = json.loads(lines[-1]).get("this_sha256")

    built_at = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lineage = {
        "built_at": built_at,
        "built_by": os.environ.get("VP_SESSION", "session/2026-06-22-vp-homepage-rebuild"),
        "parent_sha256": prev,
        "this_sha256": "",
        "changes": (sys.argv[1:] or [
            "genesis: consolidated 30 volumes into a single repo",
            "rebuilt docs/index.html (homepage) from the manifest",
            "integrated +5 volumes: eye, ear, nose, wave-computer, inheritance (docs + repro)",
            "added repro/ entries for the 5 new volumes (30/30 complete)",
            "manifest now tracks content_sha256 AND repro_sha256 per volume",
            "primitive counts corrected to volumes-only: R19 22, gamma 22, emergence 27",
            "sitemap 609->676", "added AGENTS.md AI reading guide",
        ]),
    }
    manifest["lineage"] = lineage
    # hash the manifest with this_sha256 blank, then fill (canonical: sorted keys, compact)
    canon = json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    digest = sha256_bytes(canon.encode())
    manifest["lineage"]["this_sha256"] = digest

    os.makedirs("registry", exist_ok=True)
    json.dump(manifest, open(MANIFEST, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    # append one line to the chain
    with open(LINEAGE, "a", encoding="utf-8") as f:
        f.write(json.dumps({"built_at": built_at, "built_by": lineage["built_by"],
                            "parent_sha256": prev, "this_sha256": digest,
                            "changes": lineage["changes"]}, ensure_ascii=False) + "\n")

    print(f"wrote {MANIFEST}  ({os.path.getsize(MANIFEST)} bytes)")
    print(f"volumes: {len(volumes)}  |  manifest sha256: {digest[:16]}…  |  parent: {prev}")
    print("primitive counts:", {k: v["count"] for k, v in prims.items()})

if __name__ == "__main__":
    main()
