from __future__ import annotations
import sys
from pathlib import Path
import pandas as pd
import yaml

from common import repo_root

def _read_table(p: Path) -> pd.DataFrame:
    if p.suffix.lower() == ".csv":
        return pd.read_csv(p)
    if p.suffix.lower() == ".tsv":
        return pd.read_csv(p, sep="\t")
    raise ValueError(f"unsupported: {p}")

def main() -> int:
    root = repo_root()
    cpath = root / "config" / "constraints_v1_3.yaml"
    if not cpath.exists():
        print(f"FAIL: missing {cpath}")
        return 2
    constraints = yaml.safe_load(cpath.read_text(encoding="utf-8"))

    # 1) Require checksum manifest present
    manifest_rel = constraints.get("INTEGRITY", {}).get("sha256_manifest", "checksums/SHA256SUMS.txt")
    mpath = root / manifest_rel
    if not mpath.exists():
        print(f"FAIL: missing checksum manifest: {manifest_rel}")
        return 1

    # 2) QA report must exist and show FAIL=0 (generated by scripts/run_qa.py)
    qjson = root / "qa" / "qa_report.json"
    if not qjson.exists():
        print("FAIL: missing qa/qa_report.json (run scripts/run_qa.py)")
        return 1
    import json
    q = json.loads(qjson.read_text(encoding="utf-8"))
    if int(q.get("fail", 1)) != 0 and bool(constraints.get("QA", {}).get("require_fail_zero", True)):
        print(f"FAIL: QA has fail={q.get('fail')}")
        return 1

    # 3) QC_flag columns must be PASS if present in selected tables (shortcuts and key intakes)
    require_flag = bool(constraints.get("FLAGS", {}).get("require_QC_flag_PASS", True))
    if require_flag:
        candidates = []
        # shortcuts at data/*.csv
        candidates += list((root / "data").glob("*.csv"))
        # mini set
        candidates += list((root / "data/mini/pf_whitepaper_v1_3_minidata_data").glob("*.csv"))
        # full intake set
        candidates += list((root / "data/full/datasets_v1_2").rglob("*.csv"))

        bad = 0
        checked = 0
        for p in sorted(set(candidates)):
            try:
                df = _read_table(p)
            except Exception:
                continue
            if "QC_flag" in df.columns:
                checked += 1
                vals = set(str(v).strip().upper() for v in df["QC_flag"].dropna().unique())
                if not vals.issubset({"PASS"}):
                    bad += 1
                    print(f"FAIL: QC_flag not PASS-only in {p.relative_to(root)}: {sorted(vals)}")
        if bad:
            print(f"hardgate: QC_flag check FAIL ({bad} files)")
            return 1
        print(f"hardgate: QC_flag check OK ({checked} files)")

    print("hardgate: PASS")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
